$array = 
[
["brands_id"=> 1, "name"=> "378 GT Zagato", "slug"=> "378-gt-zagato"], 
["brands_id"=> 1, "name"=> "Ace", "slug"=> "ace"], 
["brands_id"=> 1, "name"=> "Aceca", "slug"=> "aceca"], 
["brands_id"=> 1, "name"=> "Cobra", "slug"=> "cobra"], 
["brands_id"=> 1, "name"=> "12 HP Tourer", "slug"=> "12hp-tourer"], 
["brands_id"=> 1, "name"=> "2-Litre Sports Tourer", "slug"=> "2-litre"], 
["brands_id"=> 1, "name"=> "3000ME", "slug"=> "3000me"], 
["brands_id"=> 1, "name"=> "427/428/429", "slug"=> "427-428-429"], 
["brands_id"=> 1, "name"=> "Acedes-Magna", "slug"=> "acedes-magna"], 
["brands_id"=> 1, "name"=> "Centenary Eight", "slug"=> "centenary-eight"], 
["brands_id"=> 1, "name"=> "Greyhound", "slug"=> "greyhound"], 
["brands_id"=> 1, "name"=> "Six", "slug"=> "six"], 
["brands_id"=> 1, "name"=> "Sociable", "slug"=> "sociable"],

["brands_id"=> 2, "name"=> "CSX", "slug"=> "csx"],
["brands_id"=> 2, "name"=> "Integra", "slug"=> "integra"],
["brands_id"=> 2, "name"=> "MDX", "slug"=> "mdx-"],
["brands_id"=> 2, "name"=> "RSX", "slug"=> "rsx"],
["brands_id"=> 2, "name"=> "CDX", "slug"=> "cdx"],
["brands_id"=> 2, "name"=> "CL", "slug"=> "cl"],
["brands_id"=> 2, "name"=> "EL", "slug"=> "el"],
["brands_id"=> 2, "name"=> "ILX", "slug"=> "ilx"],
["brands_id"=> 2, "name"=> "Legend", "slug"=> "legend"],
["brands_id"=> 2, "name"=> "NSX", "slug"=> "nsx"],
["brands_id"=> 2, "name"=> "RDX", "slug"=> "rdx"],
["brands_id"=> 2, "name"=> "RL", "slug"=> "rl"],
["brands_id"=> 2, "name"=> "RLX", "slug"=> "rlx"],
["brands_id"=> 2, "name"=> "SLX", "slug"=> "slx"],
["brands_id"=> 2, "name"=> "TL", "slug"=> "tl"],
["brands_id"=> 2, "name"=> "TLX", "slug"=> "tlx"],
["brands_id"=> 2, "name"=> "TSX", "slug"=> "tsx"],
["brands_id"=> 2, "name"=> "Vigor", "slug"=> "vigor"],
["brands_id"=> 2, "name"=> "ZDX", "slug"=> "zdx"],

["brands_id"=> 3, "name"=> "Diplomat", "slug"=> "diplomat"],
["brands_id"=> 3, "name"=> "Trumpf Junior", "slug"=> "trumpf-junior"],
["brands_id"=> 3, "name"=> "10/20 PS", "slug"=> "10-20-ps"],
["brands_id"=> 3, "name"=> "10/25 PS", "slug"=> "10-25-ps"],
["brands_id"=> 3, "name"=> "2.5 Liter", "slug"=> "2.5liter"],
["brands_id"=> 3, "name"=> "5/11 PS", "slug"=> "5-11-ps"],
["brands_id"=> 3, "name"=> "6/24 PS", "slug"=> "6-24-ps"],
["brands_id"=> 3, "name"=> "6/25 PS", "slug"=> "6-25-ps"],
["brands_id"=> 3, "name"=> "7/17 PS", "slug"=> "7-17-ps"],
["brands_id"=> 3, "name"=> "9/24 PS", "slug"=> "9-24-ps"],
["brands_id"=> 3, "name"=> "Favorit", "slug"=> "favorit"],
["brands_id"=> 3, "name"=> "Standard", "slug"=> "standard"],

["brands_id"=> 4, "name"=> "M5", "slug"=> "m5-"],

["brands_id"=> 5, "name"=> "U5", "slug"=> "u5"],
["brands_id"=> 5, "name"=> "U6 ion", "slug"=> "u6-ion"],

 
["brands_id"=> 6, "name"=> "166", "slug"=> "166"],
["brands_id"=> 6, "name"=> "4C", "slug"=> "4c"],
["brands_id"=> 6, "name"=> "Giulia", "slug"=> "giulia"],
["brands_id"=> 6, "name"=> "Giulietta", "slug"=> "giulietta"],
["brands_id"=> 6, "name"=> "MiTo", "slug"=> "mito"],
["brands_id"=> 6, "name"=> "Stelvio", "slug"=> "stelvio"],
["brands_id"=> 6, "name"=> "105/115", "slug"=> "105115"],
["brands_id"=> 6, "name"=> "145", "slug"=> "145"],
["brands_id"=> 6, "name"=> "146", "slug"=> "146"],
["brands_id"=> 6, "name"=> "147", "slug"=> "147"],
["brands_id"=> 6, "name"=> "155", "slug"=> "155"],
["brands_id"=> 6, "name"=> "156", "slug"=> "156"],
["brands_id"=> 6, "name"=> "159", "slug"=> "159"],
["brands_id"=> 6, "name"=> "164", "slug"=> "164"],
["brands_id"=> 6, "name"=> "1900", "slug"=> "1900"],
["brands_id"=> 6, "name"=> "2600", "slug"=> "2600"],
["brands_id"=> 6, "name"=> "33", "slug"=> "33"],
["brands_id"=> 6, "name"=> "6", "slug"=> "6"],
["brands_id"=> 6, "name"=> "6C", "slug"=> "6c"],
["brands_id"=> 6, "name"=> "75", "slug"=> "75"],
["brands_id"=> 6, "name"=> "8C Competizione", "slug"=> "8c-competizione"],
["brands_id"=> 6, "name"=> "90", "slug"=> "90"],
["brands_id"=> 6, "name"=> "Alfasud", "slug"=> "alfasud"],
["brands_id"=> 6, "name"=> "Alfetta", "slug"=> "alfetta"],
["brands_id"=> 6, "name"=> "Arna", "slug"=> "arna"],
["brands_id"=> 6, "name"=> "Brera", "slug"=> "brera"],
["brands_id"=> 6, "name"=> "Disco Volante", "slug"=> "disco-volante"],
["brands_id"=> 6, "name"=> "GT", "slug"=> "gt"],
["brands_id"=> 6, "name"=> "GTA Coupe", "slug"=> "gta-coupe"],
["brands_id"=> 6, "name"=> "GTV", "slug"=> "gtv"],
["brands_id"=> 6, "name"=> "Montreal", "slug"=> "montreal"],
["brands_id"=> 6, "name"=> "RZ", "slug"=> "rz"],
["brands_id"=> 6, "name"=> "Spparent_ider", "slug"=> "spparent_ider"],
["brands_id"=> 6, "name"=> "Sprint", "slug"=> "sprint"],
["brands_id"=> 6, "name"=> "SZ", "slug"=> "sz"],
["brands_id"=> 6, "name"=> "Tonale", "slug"=> "tonale"],

["brands_id"=> 7, "name"=> "A110", "slug"=> "a110"],
["brands_id"=> 7, "name"=> "A310", "slug"=> "a310"],
["brands_id"=> 7, "name"=> "A610", "slug"=> "a610"],
["brands_id"=> 7, "name"=> "GTA", "slug"=> "gta"],


["brands_id"=> 8, "name"=> "Eagle", "slug"=> "eagle"],
["brands_id"=> 8, "name"=> "Hornet", "slug"=> "hornet"],

["brands_id"=> 9, "name"=> "HMMWV (Humvee)", "slug"=> "hmmwv-humvee"],

["brands_id"=> 10, "name"=> "21541 Stalker", "slug"=> "21541-stalker"],

["brands_id"=> 11, "name"=> "α-S (Alpha-S)", "slug"=> "alpha-s"],
["brands_id"=> 11, "name"=> "α-T (Alpha-T)", "slug"=> "alpha-t"],
["brands_id"=> 11, "name"=> "7", "slug"=> "7"],
["brands_id"=> 11, "name"=> "GT", "slug"=> "gt"],
["brands_id"=> 11, "name"=> "Lite", "slug"=> "lite"],

["brands_id"=> 12, "name"=> "Atom", "slug"=> "atom"],

["brands_id"=> 13, "name"=> "10", "slug"=> "10"],
["brands_id"=> 13, "name"=> "24", "slug"=> "24"],

["brands_id"=> 14, "name"=> "Retona", "slug"=> "retona"],
["brands_id"=> 14, "name"=> "Rocsta", "slug"=> "rocsta"],
["brands_id"=> 14, "name"=> "Topic", "slug"=> "topic"],

["brands_id"=> 15, "name"=> "DB11", "slug"=> "db11"],
["brands_id"=> 15, "name"=> "DB9", "slug"=> "db9"],
["brands_id"=> 15, "name"=> "Rapparent_ide", "slug"=> "rapparent_ide"],
["brands_id"=> 15, "name"=> "V12 Vantage", "slug"=> "v12-vantage"],
["brands_id"=> 15, "name"=> "Vanquish", "slug"=> "vanquish"],
["brands_id"=> 15, "name"=> "Bulldog", "slug"=> "bulldog"],
["brands_id"=> 15, "name"=> "Cygnet", "slug"=> "cygnet"],
["brands_id"=> 15, "name"=> "DB5", "slug"=> "db5"],
["brands_id"=> 15, "name"=> "DB7", "slug"=> "db7"],
["brands_id"=> 15, "name"=> "DB AR1", "slug"=> "db-ar1"],
["brands_id"=> 15, "name"=> "DBS", "slug"=> "dbs"],
["brands_id"=> 15, "name"=> "DBX", "slug"=> "dbx"],
["brands_id"=> 15, "name"=> "Lagonda", "slug"=> "lagonda"],
["brands_id"=> 15, "name"=> "One-77", "slug"=> "one-77"],
["brands_id"=> 15, "name"=> "Tickford Capri", "slug"=> "tickford-capri"],
["brands_id"=> 15, "name"=> "V12 Zagato", "slug"=> "v12-zagato"],
["brands_id"=> 15, "name"=> "V8 Vantage", "slug"=> "v8-vantage"],
["brands_id"=> 15, "name"=> "V8 Zagato", "slug"=> "v8-zagato"],
["brands_id"=> 15, "name"=> "Virage", "slug"=> "virage"],

["brands_id"=> 16, "name"=> "A3", "slug"=> "a3"],
["brands_id"=> 16, "name"=> "A4", "slug"=> "a4"],
["brands_id"=> 16, "name"=> "A5", "slug"=> "a5"],
["brands_id"=> 16, "name"=> "A6", "slug"=> "a6"],
["brands_id"=> 16, "name"=> "A6 allroad", "slug"=> "a6-allroad"],
["brands_id"=> 16, "name"=> "A7", "slug"=> "a7"],
["brands_id"=> 16, "name"=> "A8", "slug"=> "a8"],
["brands_id"=> 16, "name"=> "Q5", "slug"=> "q5"],
["brands_id"=> 16, "name"=> "Q7", "slug"=> "q7"],
["brands_id"=> 16, "name"=> "S5", "slug"=> "s5"],
["brands_id"=> 16, "name"=> "100", "slug"=> "100"],
["brands_id"=> 16, "name"=> "200", "slug"=> "200"],
["brands_id"=> 16, "name"=> "4000", "slug"=> "4000"],
["brands_id"=> 16, "name"=> "50", "slug"=> "50"],
["brands_id"=> 16, "name"=> "5000", "slug"=> "5000"],
["brands_id"=> 16, "name"=> "60", "slug"=> "60"],
["brands_id"=> 16, "name"=> "75", "slug"=> "75"],
["brands_id"=> 16, "name"=> "80", "slug"=> "80"],
["brands_id"=> 16, "name"=> "90", "slug"=> "90"],
["brands_id"=> 16, "name"=> "920", "slug"=> "920"],
["brands_id"=> 16, "name"=> "A1", "slug"=> "a1"],
["brands_id"=> 16, "name"=> "A1 e-tron", "slug"=> "a1-e-tron"],
["brands_id"=> 16, "name"=> "A2", "slug"=> "a2"],
["brands_id"=> 16, "name"=> "A4 allroad", "slug"=> "a4-allroad"],
["brands_id"=> 16, "name"=> "A6 e-tron", "slug"=> "a6-e-tron"],
["brands_id"=> 16, "name"=> "Cabriolet", "slug"=> "cabriolet"],
["brands_id"=> 16, "name"=> "Coupe", "slug"=> "coupe"],
["brands_id"=> 16, "name"=> "e-tron", "slug"=> "e-tron"],
["brands_id"=> 16, "name"=> "e-tron GT", "slug"=> "e-tron-gt"],
["brands_id"=> 16, "name"=> "e-tron S", "slug"=> "e-tron-s"],
["brands_id"=> 16, "name"=> "e-tron Sportback", "slug"=> "e-tron-sportback"],
["brands_id"=> 16, "name"=> "e-tron S Sportback", "slug"=> "e-tron-s-sportback"],
["brands_id"=> 16, "name"=> "Fox", "slug"=> "fox"],
["brands_id"=> 16, "name"=> "Front", "slug"=> "front"],
["brands_id"=> 16, "name"=> "NSU RO 80", "slug"=> "nsu-ro-80"],
["brands_id"=> 16, "name"=> "Q2", "slug"=> "q2"],
["brands_id"=> 16, "name"=> "Q2 e-tron", "slug"=> "q2-e-tron"],
["brands_id"=> 16, "name"=> "Q3", "slug"=> "q3"],
["brands_id"=> 16, "name"=> "Q3 Sportback", "slug"=> "q3-sportback"],
["brands_id"=> 16, "name"=> "Q4 e-tron", "slug"=> "q4-"],
["brands_id"=> 16, "name"=> "Q4 Sportback e-tron", "slug"=> "q4-sportback-"],
["brands_id"=> 16, "name"=> "Q5 Sportback", "slug"=> "q5-sportback"],
["brands_id"=> 16, "name"=> "Q8", "slug"=> "q8"],
["brands_id"=> 16, "name"=> "Quattro", "slug"=> "quattro"],
["brands_id"=> 16, "name"=> "R8", "slug"=> "r8"],
["brands_id"=> 16, "name"=> "RS2", "slug"=> "rs2"],
["brands_id"=> 16, "name"=> "RS3", "slug"=> "rs3"],
["brands_id"=> 16, "name"=> "RS4", "slug"=> "rs4"],
["brands_id"=> 16, "name"=> "RS5", "slug"=> "rs5"],
["brands_id"=> 16, "name"=> "RS6", "slug"=> "rs6"],
["brands_id"=> 16, "name"=> "RS7 Sportback", "slug"=> "rs7-sportback"],
["brands_id"=> 16, "name"=> "RS e-tron GT", "slug"=> "rs-e-tron-gt"],
["brands_id"=> 16, "name"=> "RS Q3", "slug"=> "rs-q3"],
["brands_id"=> 16, "name"=> "RS Q3 Sportback", "slug"=> "rs-q3-sportback"],
["brands_id"=> 16, "name"=> "RS Q8", "slug"=> "rs-q8"],
["brands_id"=> 16, "name"=> "S1", "slug"=> "s1"],
["brands_id"=> 16, "name"=> "S2", "slug"=> "s2"],
["brands_id"=> 16, "name"=> "S3", "slug"=> "s3"],
["brands_id"=> 16, "name"=> "S4", "slug"=> "s4"],
["brands_id"=> 16, "name"=> "S6", "slug"=> "s6"],
["brands_id"=> 16, "name"=> "S7", "slug"=> "s7"],
["brands_id"=> 16, "name"=> "S8", "slug"=> "s8"],
["brands_id"=> 16, "name"=> "Sport Quattro", "slug"=> "sport-quattro"],
["brands_id"=> 16, "name"=> "SQ2", "slug"=> "sq2"],
["brands_id"=> 16, "name"=> "SQ5", "slug"=> "sq5"],
["brands_id"=> 16, "name"=> "SQ5 Sportback", "slug"=> "sq5-sportback"],
["brands_id"=> 16, "name"=> "SQ7", "slug"=> "sq7"],
["brands_id"=> 16, "name"=> "SQ8", "slug"=> "sq8"],
["brands_id"=> 16, "name"=> "Super 90", "slug"=> "super-90"],
["brands_id"=> 16, "name"=> "TT", "slug"=> "tt"],
["brands_id"=> 16, "name"=> "TT RS", "slug"=> "tt-rs"],
["brands_id"=> 16, "name"=> "TTS", "slug"=> "tts"],
["brands_id"=> 16, "name"=> "Typ A", "slug"=> "typ-a"],
["brands_id"=> 16, "name"=> "Typ B", "slug"=> "typ-b"],
["brands_id"=> 16, "name"=> "Typ C "Alpensieger"", "slug"=> "typ-c-alpensieger"],
["brands_id"=> 16, "name"=> "Typ E", "slug"=> "typ-e"],
["brands_id"=> 16, "name"=> "Typ K", "slug"=> "typ-k"],
["brands_id"=> 16, "name"=> "Typ M", "slug"=> "typ-m"],
["brands_id"=> 16, "name"=> "Typ P", "slug"=> "typ-p"],
["brands_id"=> 16, "name"=> "Typ R", "slug"=> "typ-r"],
["brands_id"=> 16, "name"=> "Typ SS", "slug"=> "typ-ss"],
["brands_id"=> 16, "name"=> "Typ T", "slug"=> "typ-t"],
["brands_id"=> 16, "name"=> "V8", "slug"=> "v8"],

["brands_id"=> 17, "name"=> "Arsenal", "slug"=> "arsenal"],
["brands_id"=> 17, "name"=> "Komendant", "slug"=> "komendant"],
["brands_id"=> 17, "name"=> "Senat", "slug"=> "senat"],

["brands_id"=> 18, "name"=> "Maestro", "slug"=> "maestro"],
["brands_id"=> 18, "name"=> "Mini", "slug"=> "mini"],
["brands_id"=> 18, "name"=> "Princess", "slug"=> "princess"],
["brands_id"=> 18, "name"=> "Allegro", "slug"=> "allegro"],
["brands_id"=> 18, "name"=> "Ambassador", "slug"=> "ambassador"],
["brands_id"=> 18, "name"=> "FL2", "slug"=> "fl2"],
["brands_id"=> 18, "name"=> "Maxi", "slug"=> "maxi"],
["brands_id"=> 18, "name"=> "Metro", "slug"=> "metro"],
["brands_id"=> 18, "name"=> "Montego", "slug"=> "montego"],

["brands_id"=> 19, "name"=> "3000", "slug"=> "3000"],
["brands_id"=> 19, "name"=> "Sprite", "slug"=> "sprite"],

["brands_id"=> 20, "name"=> "A 112", "slug"=> "a-112"],

["brands_id"=> 21, "name"=> "11", "slug"=> "11"],

["brands_id"=> 22, "name"=> "2160", "slug"=> "2160"],
["brands_id"=> 22, "name"=> "2163", "slug"=> "2163"],
["brands_id"=> 22, "name"=> "3101", "slug"=> "3101"],

["brands_id"=> 23, "name"=> "Aziz", "slug"=> "aziz"],

["brands_id"=> 24, "name"=> "D20", "slug"=> "d20"],
["brands_id"=> 24, "name"=> "X25", "slug"=> "x25"],
["brands_id"=> 24, "name"=> "X55", "slug"=> "x55"],
["brands_id"=> 24, "name"=> "205", "slug"=> "205"],
["brands_id"=> 24, "name"=> "306", "slug"=> "306"],
["brands_id"=> 24, "name"=> "307", "slug"=> "307"],
["brands_id"=> 24, "name"=> "A1", "slug"=> "a1"],
["brands_id"=> 24, "name"=> "Big Cat", "slug"=> "big-cat"],
["brands_id"=> 24, "name"=> "BJ20", "slug"=> "bj20"],
["brands_id"=> 24, "name"=> "BJ2020", "slug"=> "bj2020"],
["brands_id"=> 24, "name"=> "BJ2023", "slug"=> "bj2023"],
["brands_id"=> 24, "name"=> "BJ2030", "slug"=> "bj2030"],
["brands_id"=> 24, "name"=> "BJ2033", "slug"=> "bj2033"],
["brands_id"=> 24, "name"=> "BJ212", "slug"=> "bj212"],
["brands_id"=> 24, "name"=> "BJ30", "slug"=> "bj30"],
["brands_id"=> 24, "name"=> "BJ40", "slug"=> "bj40"],
["brands_id"=> 24, "name"=> "BJ40L", "slug"=> "bj40l"],
["brands_id"=> 24, "name"=> "BJ80", "slug"=> "bj80"],
["brands_id"=> 24, "name"=> "BJ90", "slug"=> "bj90"],
["brands_id"=> 24, "name"=> "E150", "slug"=> "e150"],
["brands_id"=> 24, "name"=> "EC", "slug"=> "ec"],
["brands_id"=> 24, "name"=> "EC3", "slug"=> "ec3-"],
["brands_id"=> 24, "name"=> "EC5", "slug"=> "ec5"],
["brands_id"=> 24, "name"=> "EU260", "slug"=> "eu260"],
["brands_id"=> 24, "name"=> "EU5", "slug"=> "eu5"],
["brands_id"=> 24, "name"=> "EX", "slug"=> "ex"],
["brands_id"=> 24, "name"=> "EX3", "slug"=> "ex3"],
["brands_id"=> 24, "name"=> "F40", "slug"=> "f40"],
["brands_id"=> 24, "name"=> "Jeep Cherokee 2500", "slug"=> "jeep-cherokee-2500"],
["brands_id"=> 24, "name"=> "Kitten", "slug"=> "kitten"],
["brands_id"=> 24, "name"=> "Lite", "slug"=> "lite-"],
["brands_id"=> 24, "name"=> "Luba (XB624)", "slug"=> "luba-xb624"],
["brands_id"=> 24, "name"=> "M20", "slug"=> "m20"],
["brands_id"=> 24, "name"=> "M30", "slug"=> "m30"],
["brands_id"=> 24, "name"=> "M35", "slug"=> "m35"],
["brands_id"=> 24, "name"=> "M50F", "slug"=> "m50f"],
["brands_id"=> 24, "name"=> "M60", "slug"=> "m60"],
["brands_id"=> 24, "name"=> "Qishi", "slug"=> "qishi"],
["brands_id"=> 24, "name"=> "S50", "slug"=> "s50"],
["brands_id"=> 24, "name"=> "Senova D50", "slug"=> "senova-d50"],
["brands_id"=> 24, "name"=> "Senova D70", "slug"=> "senova-d70"],
["brands_id"=> 24, "name"=> "X3", "slug"=> "x3-"],
["brands_id"=> 24, "name"=> "X35", "slug"=> "x35"],
["brands_id"=> 24, "name"=> "X5", "slug"=> "x5"],
["brands_id"=> 24, "name"=> "X65", "slug"=> "x65"],
["brands_id"=> 24, "name"=> "X7", "slug"=> "x7"],
["brands_id"=> 24, "name"=> "Yusheng 007", "slug"=> "yusheng-007"],

["brands_id"=> 25, "name"=> "Qute", "slug"=> "qute"],
["brands_id"=> 25, "name"=> "Maxima", "slug"=> "maxima-"],

["brands_id"=> 26, "name"=> "BD-1322", "slug"=> "bd-1322"],

["brands_id"=> 27, "name"=> "Fenix 1044", "slug"=> "fenix-1044"],
["brands_id"=> 27, "name"=> "Fenix 1065", "slug"=> "fenix-1065"],
["brands_id"=> 27, "name"=> "Fenix 3346", "slug"=> "fenix-3346"],
["brands_id"=> 27, "name"=> "Fenix 33462", "slug"=> "fenix-33462"],
["brands_id"=> 27, "name"=> "Fenix 33468", "slug"=> "fenix-33468"],
["brands_id"=> 27, "name"=> "Tonik", "slug"=> "tonik"],

["brands_id"=> 28, "name"=> "Bentayga", "slug"=> "bentayga"],
["brands_id"=> 28, "name"=> "Continental", "slug"=> "continental"],
["brands_id"=> 28, "name"=> "Continental GT", "slug"=> "continental-gt"],
["brands_id"=> 28, "name"=> "Flying Spur", "slug"=> "flying-spur"],
["brands_id"=> 28, "name"=> "Mulsanne", "slug"=> "mulsanne"],
["brands_id"=> 28, "name"=> "Arnage", "slug"=> "arnage"],
["brands_id"=> 28, "name"=> "Azure", "slug"=> "azure"],
["brands_id"=> 28, "name"=> "Brooklands", "slug"=> "brooklands"],
["brands_id"=> 28, "name"=> "Eight", "slug"=> "eight"],
["brands_id"=> 28, "name"=> "Mark VI", "slug"=> "mark-vi"],
["brands_id"=> 28, "name"=> "R Type", "slug"=> "r-type"],
["brands_id"=> 28, "name"=> "S", "slug"=> "s"],
["brands_id"=> 28, "name"=> "T-Series", "slug"=> "t-series"],
["brands_id"=> 28, "name"=> "Turbo R", "slug"=> "turbo-r"],

["brands_id"=> 29, "name"=> "Freeclimber", "slug"=> "freeclimber"],

["brands_id"=> 30, "name"=> "T33", "slug"=> "t33"],
["brands_id"=> 30, "name"=> "T77", "slug"=> "t77"],
["brands_id"=> 30, "name"=> "T99", "slug"=> "t99"],
["brands_id"=> 30, "name"=> "NAT", "slug"=> "nat"],

["brands_id"=> 31, "name"=> "Vintage", "slug"=> "vintage"],

["brands_id"=> 32, "name"=> "CD", "slug"=> "cd"],
["brands_id"=> 32, "name"=> "Type 3", "slug"=> "type-3"],

["brands_id"=> 33, "name"=> "1 series", "slug"=> "1-series"],
["brands_id"=> 33, "name"=> "2 series", "slug"=> "2-series"],
["brands_id"=> 33, "name"=> "3 series", "slug"=> "3-series"],
["brands_id"=> 33, "name"=> "4 series", "slug"=> "4-series"],
["brands_id"=> 33, "name"=> "5 series", "slug"=> "5-series"],
["brands_id"=> 33, "name"=> "6 series", "slug"=> "6-series"],
["brands_id"=> 33, "name"=> "7 series", "slug"=> "7-series"],
["brands_id"=> 33, "name"=> "M3", "slug"=> "m3"],
["brands_id"=> 33, "name"=> "M4", "slug"=> "m4"],
["brands_id"=> 33, "name"=> "M5", "slug"=> "m5"],
["brands_id"=> 33, "name"=> "X1", "slug"=> "x1"],
["brands_id"=> 33, "name"=> "X3", "slug"=> "x3"],
["brands_id"=> 33, "name"=> "X5", "slug"=> "x5"],
["brands_id"=> 33, "name"=> "X5 M", "slug"=> "x5-m"],
["brands_id"=> 33, "name"=> "X6", "slug"=> "x6"],
["brands_id"=> 33, "name"=> "X6 M", "slug"=> "x6-m"],
["brands_id"=> 33, "name"=> "X7", "slug"=> "x7"],
["brands_id"=> 33, "name"=> "Z3", "slug"=> "z3"],
["brands_id"=> 33, "name"=> "Z4", "slug"=> "z4"],
["brands_id"=> 33, "name"=> "02 (E10)", "slug"=> "02-e10"],
["brands_id"=> 33, "name"=> "1M", "slug"=> "1m"],
["brands_id"=> 33, "name"=> "2000 C/CS", "slug"=> "2000-ccs"],
["brands_id"=> 33, "name"=> "315", "slug"=> "315"],
["brands_id"=> 33, "name"=> "3/15", "slug"=> "3-15"],
["brands_id"=> 33, "name"=> "3200", "slug"=> "3200"],
["brands_id"=> 33, "name"=> "321", "slug"=> "321"],
["brands_id"=> 33, "name"=> "326", "slug"=> "326"],
["brands_id"=> 33, "name"=> "327", "slug"=> "327"],
["brands_id"=> 33, "name"=> "340", "slug"=> "340"],
["brands_id"=> 33, "name"=> "501", "slug"=> "501"],
["brands_id"=> 33, "name"=> "502", "slug"=> "502"],
["brands_id"=> 33, "name"=> "503", "slug"=> "503"],
["brands_id"=> 33, "name"=> "507", "slug"=> "507"],
["brands_id"=> 33, "name"=> "600", "slug"=> "600"],
["brands_id"=> 33, "name"=> "700", "slug"=> "700"],
["brands_id"=> 33, "name"=> "8 series", "slug"=> "8-series"],
["brands_id"=> 33, "name"=> "E3", "slug"=> "e3"],
["brands_id"=> 33, "name"=> "E9", "slug"=> "e9"],
["brands_id"=> 33, "name"=> "i3", "slug"=> "i3"],
["brands_id"=> 33, "name"=> "i4", "slug"=> "i4"],
["brands_id"=> 33, "name"=> "I5", "slug"=> "i5"],
["brands_id"=> 33, "name"=> "i7", "slug"=> "i7"],
["brands_id"=> 33, "name"=> "i8", "slug"=> "i8"],
["brands_id"=> 33, "name"=> "iX", "slug"=> "ix"],
["brands_id"=> 33, "name"=> "M1", "slug"=> "m1"],
["brands_id"=> 33, "name"=> "M2", "slug"=> "m2"],
["brands_id"=> 33, "name"=> "M6", "slug"=> "m6"],
["brands_id"=> 33, "name"=> "M8", "slug"=> "m8"],
["brands_id"=> 33, "name"=> "Nazca", "slug"=> "nazca"],
["brands_id"=> 33, "name"=> "New Class", "slug"=> "new-class"],
["brands_id"=> 33, "name"=> "X2", "slug"=> "x2"],
["brands_id"=> 33, "name"=> "X2 M", "slug"=> "x2-m"],
["brands_id"=> 33, "name"=> "X3 M", "slug"=> "x3-m"],
["brands_id"=> 33, "name"=> "X4", "slug"=> "x4"],
["brands_id"=> 33, "name"=> "X4 M", "slug"=> "x4-m"],
["brands_id"=> 33, "name"=> "XM", "slug"=> "xm"],
["brands_id"=> 33, "name"=> "Z1", "slug"=> "z1"],
["brands_id"=> 33, "name"=> "Z3 M", "slug"=> "z3-m"],
["brands_id"=> 33, "name"=> "Z4 M", "slug"=> "z4-m"],
["brands_id"=> 33, "name"=> "Z8", "slug"=> "z8"],

["brands_id"=> 34, "name"=> "B10", "slug"=> "b10"],
["brands_id"=> 34, "name"=> "B11", "slug"=> "b11"],
["brands_id"=> 34, "name"=> "B12", "slug"=> "b12"],
["brands_id"=> 34, "name"=> "D10", "slug"=> "d10"],
["brands_id"=> 34, "name"=> "Roadster", "slug"=> "roadster"],
["brands_id"=> 34, "name"=> "XD3", "slug"=> "xd"],
["brands_id"=> 34, "name"=> "B3", "slug"=> "b3"],
["brands_id"=> 34, "name"=> "B4", "slug"=> "b4"],
["brands_id"=> 34, "name"=> "B5", "slug"=> "b5"],
["brands_id"=> 34, "name"=> "B6", "slug"=> "b6"],
["brands_id"=> 34, "name"=> "B7", "slug"=> "b7"],
["brands_id"=> 34, "name"=> "B8", "slug"=> "b8"],
["brands_id"=> 34, "name"=> "B9", "slug"=> "b9"],
["brands_id"=> 34, "name"=> "C1", "slug"=> "c1"],
["brands_id"=> 34, "name"=> "C2", "slug"=> "c2"],
["brands_id"=> 34, "name"=> "D3", "slug"=> "d3"],
["brands_id"=> 34, "name"=> "D4", "slug"=> "d4"],
["brands_id"=> 34, "name"=> "D5", "slug"=> "d5"],
["brands_id"=> 34, "name"=> "XB7", "slug"=> "xb7"],
["brands_id"=> 34, "name"=> "XD4", "slug"=> "xd4"],

["brands_id"=> 35, "name"=> "2000", "slug"=> "2000"],
["brands_id"=> 35, "name"=> "Hansa 1100", "slug"=> "hansa-1100"],

["brands_id"=> 36, "name"=> "7.3S", "slug"=> "73s"],
["brands_id"=> 36, "name"=> "ML 63 Biturbo", "slug"=> "ml-63-biturbo"],
["brands_id"=> 36, "name"=> "M V12", "slug"=> "m-v12"],
["brands_id"=> 36, "name"=> "SV12", "slug"=> "sv12"],

["brands_id"=> 37, "name"=> "Brio", "slug"=> "brio"],
["brands_id"=> 37, "name"=> "Taos", "slug"=> "taos"],

["brands_id"=> 38, "name"=> "V5", "slug"=> "v5"],
["brands_id"=> 38, "name"=> "Dolphin", "slug"=> "dolphin"],
["brands_id"=> 38, "name"=> "E5", "slug"=> "e5"],
["brands_id"=> 38, "name"=> "FRV (BS2)", "slug"=> "frv-bs2"],
["brands_id"=> 38, "name"=> "H230", "slug"=> "h230"],
["brands_id"=> 38, "name"=> "H3", "slug"=> "h3"],
["brands_id"=> 38, "name"=> "H530", "slug"=> "h530"],
["brands_id"=> 38, "name"=> "M1 (BS6)", "slug"=> "m1-bs6"],
["brands_id"=> 38, "name"=> "M2 (BS4)", "slug"=> "m2-bs4"],
["brands_id"=> 38, "name"=> "M3 (BC3)", "slug"=> "m3-bc3"],
["brands_id"=> 38, "name"=> "V3", "slug"=> "v3"],
["brands_id"=> 38, "name"=> "V6", "slug"=> "v6"],
["brands_id"=> 38, "name"=> "V7", "slug"=> "v7"],

["brands_id"=> 39, "name"=> "Blenheim", "slug"=> "blenheim"],
["brands_id"=> 39, "name"=> "Blenheim Speedster", "slug"=> "blenheim-speedster"],
["brands_id"=> 39, "name"=> "Fighter", "slug"=> "fighter"],

["brands_id"=> 40, "name"=> "Geneva", "slug"=> "geneva"],
["brands_id"=> 40, "name"=> "La Joya", "slug"=> "la-joya"],

["brands_id"=> 41, "name"=> "Chiron", "slug"=> "chiron"],
["brands_id"=> 41, "name"=> "Veyron 16.4", "slug"=> "veyron-164"],
["brands_id"=> 41, "name"=> "Bolparent_ide", "slug"=> "bolparent_ide"],
["brands_id"=> 41, "name"=> "Centodieci", "slug"=> "centodieci"],
["brands_id"=> 41, "name"=> "Divo", "slug"=> "divo"],
["brands_id"=> 41, "name"=> "EB 110", "slug"=> "eb-110"],
["brands_id"=> 41, "name"=> "EB 112", "slug"=> "eb-112"],
["brands_id"=> 41, "name"=> "La Voiture Noire", "slug"=> "la-voiture-noire"],
["brands_id"=> 41, "name"=> "Type 55", "slug"=> "type-55"],

["brands_id"=> 42, "name"=> "Enclave", "slug"=> "enclave"],
["brands_id"=> 42, "name"=> "Encore", "slug"=> "encore"],
["brands_id"=> 42, "name"=> "LaCrosse", "slug"=> "lacrosse"],
["brands_id"=> 42, "name"=> "Century", "slug"=> "century"],
["brands_id"=> 42, "name"=> "Electra", "slug"=> "electra"],
["brands_id"=> 42, "name"=> "Electra E4", "slug"=> "electra-e4"],
["brands_id"=> 42, "name"=> "Electra E5", "slug"=> "electra-e5"],
["brands_id"=> 42, "name"=> "Encore GX", "slug"=> "encore-gx"],
["brands_id"=> 42, "name"=> "Envision", "slug"=> "envision"],
["brands_id"=> 42, "name"=> "Estate Wagon", "slug"=> "estate-wagon"],
["brands_id"=> 42, "name"=> "Excelle", "slug"=> "excelle"],
["brands_id"=> 42, "name"=> "GL8", "slug"=> "gl8"],
["brands_id"=> 42, "name"=> "GS", "slug"=> "gs"],
["brands_id"=> 42, "name"=> "LeSabre", "slug"=> "lesabre"],
["brands_id"=> 42, "name"=> "Limited", "slug"=> "limited"],
["brands_id"=> 42, "name"=> "Lucerne", "slug"=> "lucerne"],
["brands_id"=> 42, "name"=> "Park Avenue", "slug"=> "park-avenue"],
["brands_id"=> 42, "name"=> "Rainier", "slug"=> "rainier"],
["brands_id"=> 42, "name"=> "Reatta", "slug"=> "reatta"],
["brands_id"=> 42, "name"=> "Regal", "slug"=> "regal"],
["brands_id"=> 42, "name"=> "Rendezvous", "slug"=> "rendezvous"],
["brands_id"=> 42, "name"=> "Riviera", "slug"=> "riviera"],
["brands_id"=> 42, "name"=> "Roadmaster", "slug"=> "roadmaster"],
["brands_id"=> 42, "name"=> "Skyhawk", "slug"=> "skyhawk"],
["brands_id"=> 42, "name"=> "Skylark", "slug"=> "skylark"],
["brands_id"=> 42, "name"=> "Special", "slug"=> "special"],
["brands_id"=> 42, "name"=> "Super", "slug"=> "super"],
["brands_id"=> 42, "name"=> "Terraza", "slug"=> "terraza"],
["brands_id"=> 42, "name"=> "Verano", "slug"=> "verano"],
["brands_id"=> 42, "name"=> "Wildcat", "slug"=> "wildcat"],
 
["brands_id"=> 43, "name"=> "F3", "slug"=> "f3"],
["brands_id"=> 43, "name"=> "F6", "slug"=> "f6"],
["brands_id"=> 43, "name"=> "Atto 3", "slug"=> "atto-3"],
["brands_id"=> 43, "name"=> "D1", "slug"=> "d1"],
["brands_id"=> 43, "name"=> "E5", "slug"=> "e5"],
["brands_id"=> 43, "name"=> "E6", "slug"=> "e6"],
["brands_id"=> 43, "name"=> "F0", "slug"=> "f0"],
["brands_id"=> 43, "name"=> "F5", "slug"=> "f5"],
["brands_id"=> 43, "name"=> "F7 SuRui", "slug"=> "f7-surui"],
["brands_id"=> 43, "name"=> "F8 (S8)", "slug"=> "f8-s8"],
["brands_id"=> 43, "name"=> "Flyer", "slug"=> "flyer"],
["brands_id"=> 43, "name"=> "G3", "slug"=> "g3"],
["brands_id"=> 43, "name"=> "G6", "slug"=> "g6"],
["brands_id"=> 43, "name"=> "Han", "slug"=> "han"],
["brands_id"=> 43, "name"=> "L3", "slug"=> "l3"],
["brands_id"=> 43, "name"=> "M6", "slug"=> "m6"],
["brands_id"=> 43, "name"=> "S6", "slug"=> "s6"],
["brands_id"=> 43, "name"=> "Seal", "slug"=> "seal"],
["brands_id"=> 43, "name"=> "Song", "slug"=> "song"],
["brands_id"=> 43, "name"=> "Song Plus", "slug"=> "song-plus"],
["brands_id"=> 43, "name"=> "Tang", "slug"=> "tang"],
["brands_id"=> 43, "name"=> "Yuan", "slug"=> "yuan"],
["brands_id"=> 43, "name"=> "Yuan Plus", "slug"=> "yuan-plus"],

["brands_id"=> 44, "name"=> "BD132J (CoCo)", "slug"=> "bd132j-coco"],
["brands_id"=> 44, "name"=> "BD326J (Moca)", "slug"=> "bd326j-moca"],

["brands_id"=> 45, "name"=> "BLS", "slug"=> "bls"],
["brands_id"=> 45, "name"=> "CTS", "slug"=> "cts"],
["brands_id"=> 45, "name"=> "Escalade", "slug"=> "escalade"],
["brands_id"=> 45, "name"=> "SRX", "slug"=> "srx"],
["brands_id"=> 45, "name"=> "STS", "slug"=> "sts"],
["brands_id"=> 45, "name"=> "Allante", "slug"=> "allante"],
["brands_id"=> 45, "name"=> "ATS", "slug"=> "ats"],
["brands_id"=> 45, "name"=> "ATS-V", "slug"=> "ats-v"],
["brands_id"=> 45, "name"=> "Brougham", "slug"=> "brougham"],
["brands_id"=> 45, "name"=> "Catera", "slug"=> "catera"],
["brands_id"=> 45, "name"=> "CT4", "slug"=> "ct4"],
["brands_id"=> 45, "name"=> "CT4-V", "slug"=> "ct4-v"],
["brands_id"=> 45, "name"=> "CT5", "slug"=> "ct5"],
["brands_id"=> 45, "name"=> "CT5-V", "slug"=> "ct5-v"],
["brands_id"=> 45, "name"=> "CT6", "slug"=> "ct6"],
["brands_id"=> 45, "name"=> "CTS-V", "slug"=> "cts-v"],
["brands_id"=> 45, "name"=> "DeVille", "slug"=> "deville"],
["brands_id"=> 45, "name"=> "DTS", "slug"=> "dts"],
["brands_id"=> 45, "name"=> "Eldorado", "slug"=> "eldorado"],
["brands_id"=> 45, "name"=> "ELR", "slug"=> "elr"],
["brands_id"=> 45, "name"=> "Fleetwood", "slug"=> "fleetwood"],
["brands_id"=> 45, "name"=> "LSE", "slug"=> "lse"],
["brands_id"=> 45, "name"=> "Series 62", "slug"=> "series-62"],
["brands_id"=> 45, "name"=> "Seville", "slug"=> "seville"],
["brands_id"=> 45, "name"=> "Sixty Special", "slug"=> "sixty-special"],
["brands_id"=> 45, "name"=> "XLR", "slug"=> "xlr"],
["brands_id"=> 45, "name"=> "XT4", "slug"=> "xt4"],
["brands_id"=> 45, "name"=> "XT5", "slug"=> "xt5"],
["brands_id"=> 45, "name"=> "XT6", "slug"=> "xt6"],
["brands_id"=> 45, "name"=> "XTS", "slug"=> "xts"],

["brands_id"=> 46, "name"=> "C12", "slug"=> "c12"],

["brands_id"=> 47, "name"=> "FX4", "slug"=> "fx4"],

["brands_id"=> 48, "name"=> "21", "slug"=> "21"],
["brands_id"=> 48, "name"=> "CSR", "slug"=> "csr"],
["brands_id"=> 48, "name"=> "Seven", "slug"=> "seven"],

["brands_id"=> 49, "name"=> "Benni", "slug"=> "benni"],

["brands_id"=> 50, "name"=> "Alsvin V7", "slug"=> "alsvin-v7"],
["brands_id"=> 50, "name"=> "Benni", "slug"=> "benni"],
["brands_id"=> 50, "name"=> "CS 15", "slug"=> "cs-15"],
["brands_id"=> 50, "name"=> "CS 35", "slug"=> "cs-35"],
["brands_id"=> 50, "name"=> "CS 35 PLUS", "slug"=> "cs-35plus"],
["brands_id"=> 50, "name"=> "CS 55", "slug"=> "cs-55"],
["brands_id"=> 50, "name"=> "CS 75", "slug"=> "cs-75"],
["brands_id"=> 50, "name"=> "CS 75 Plus", "slug"=> "cs-75-plus"],
["brands_id"=> 50, "name"=> "CS 85 Coupe", "slug"=> "cs-85-coupe"],
["brands_id"=> 50, "name"=> "CS 95", "slug"=> "cs-95"],
["brands_id"=> 50, "name"=> "Eado", "slug"=> "eado"],
["brands_id"=> 50, "name"=> "Eado DT", "slug"=> "eado-dt"],
["brands_id"=> 50, "name"=> "Eado Plus", "slug"=> "eado-plus"],
["brands_id"=> 50, "name"=> "F 70", "slug"=> "f-70"],
["brands_id"=> 50, "name"=> "Honor", "slug"=> "honor"],
["brands_id"=> 50, "name"=> "Raeton", "slug"=> "raeton"],
["brands_id"=> 50, "name"=> "Uni-T", "slug"=> "uni-t"],
["brands_id"=> 50, "name"=> "Alsvin V3", "slug"=> "alsvin-v3"],
["brands_id"=> 50, "name"=> "Alsvin V5", "slug"=> "alsvin-v5"],
["brands_id"=> 50, "name"=> "Benben E-star", "slug"=> "benben-e-star"],
["brands_id"=> 50, "name"=> "CM-8", "slug"=> "cm-8"],
["brands_id"=> 50, "name"=> "CS 55 Plus", "slug"=> "cs-55-plus"],
["brands_id"=> 50, "name"=> "CX 20", "slug"=> "cx20"],
["brands_id"=> 50, "name"=> "E-Pro", "slug"=> "e-pro"],
["brands_id"=> 50, "name"=> "E-Rock", "slug"=> "e-rock"],
["brands_id"=> 50, "name"=> "Oshan (Auchan) A600", "slug"=> "oshan-auchan-a600"],
["brands_id"=> 50, "name"=> "SC 1030", "slug"=> "sc-1030"],
["brands_id"=> 50, "name"=> "SC 6360A", "slug"=> "sc-6360a"],
["brands_id"=> 50, "name"=> "Uni-K", "slug"=> "uni-k"],
["brands_id"=> 50, "name"=> "Uni-V", "slug"=> "uni-v"],
["brands_id"=> 50, "name"=> "Z-Shine", "slug"=> "z-shine"],

["brands_id"=> 51, "name"=> "Flying", "slug"=> "flying"],
["brands_id"=> 51, "name"=> "SUV (CS6)", "slug"=> "suv-cs6"],

["brands_id"=> 52, "name"=> "parent_ideal", "slug"=> "parent_ideal"],

["brands_id"=> 53, "name"=> "Amulet (A15)", "slug"=> "amulet-a15"],
["brands_id"=> 53, "name"=> "Fora (A21)", "slug"=> "fora-a21"],
["brands_id"=> 53, "name"=> "Fulwin 2", "slug"=> "fulwin-2"],
["brands_id"=> 53, "name"=> "Sweet (QQ)", "slug"=> "sweet-qq"],
["brands_id"=> 53, "name"=> "Tiggo 2", "slug"=> "tiggo-2"],
["brands_id"=> 53, "name"=> "Tiggo 4 Pro", "slug"=> "tiggo-4-pro"],
["brands_id"=> 53, "name"=> "Tiggo 7", "slug"=> "tiggo-7"],
["brands_id"=> 53, "name"=> "Tiggo 7 Pro", "slug"=> "tiggo-7-pro"],
["brands_id"=> 53, "name"=> "Tiggo (T11)", "slug"=> "tiggo-t11"],
["brands_id"=> 53, "name"=> "Arrizo 3", "slug"=> "arrizo-3"],
["brands_id"=> 53, "name"=> "Arrizo 5", "slug"=> "arrizo-5"],
["brands_id"=> 53, "name"=> "Arrizo 7", "slug"=> "arrizo-7"],
["brands_id"=> 53, "name"=> "B13", "slug"=> "b13"],
["brands_id"=> 53, "name"=> "Big Ant", "slug"=> "big-ant"],
["brands_id"=> 53, "name"=> "Bonus 3 (E3/A19)", "slug"=> "bonus-3-e3a19"],
["brands_id"=> 53, "name"=> "Bonus (A13)", "slug"=> "bonus-a13"],
["brands_id"=> 53, "name"=> "CrossEastar (B14)", "slug"=> "crosseastar-b14"],
["brands_id"=> 53, "name"=> "E5", "slug"=> "e5"],
["brands_id"=> 53, "name"=> "IndiS (S18D)", "slug"=> "indis-s18d"],
["brands_id"=> 53, "name"=> "Karry", "slug"=> "karry"],
["brands_id"=> 53, "name"=> "Kimo (A1)", "slug"=> "kimo-a1"],
["brands_id"=> 53, "name"=> "M11 (A3)", "slug"=> "m11-a3"],
["brands_id"=> 53, "name"=> "Oriental Son (B11)", "slug"=> "oriental-son-b11"],
["brands_id"=> 53, "name"=> "QQ6 (S21)", "slug"=> "qq6-s21"],
["brands_id"=> 53, "name"=> "QQme", "slug"=> "qqme"],
["brands_id"=> 53, "name"=> "Tiggo 2 Pro", "slug"=> "tiggo-2-pro"],
["brands_id"=> 53, "name"=> "Tiggo 3", "slug"=> "tiggo-3"],
["brands_id"=> 53, "name"=> "Tiggo 4", "slug"=> "tiggo-4"],
["brands_id"=> 53, "name"=> "Tiggo 5", "slug"=> "tiggo-5"],
["brands_id"=> 53, "name"=> "Tiggo 8", "slug"=> "tiggo-8"],
["brands_id"=> 53, "name"=> "Tiggo 8pro", "slug"=> "tiggo-8pro"],
["brands_id"=> 53, "name"=> "Tiggo 9", "slug"=> "tiggo-9"],
["brands_id"=> 53, "name"=> "Very (A13)", "slug"=> "very-a13"],
["brands_id"=> 53, "name"=> "Windcloud (A11)", "slug"=> "windcloud-a11"],

["brands_id"=> 54, "name"=> "Aveo", "slug"=> "aveo"],
["brands_id"=> 54, "name"=> "Camaro", "slug"=> "camaro"],
["brands_id"=> 54, "name"=> "Captiva", "slug"=> "captiva"],
["brands_id"=> 54, "name"=> "Corvette", "slug"=> "corvette"],
["brands_id"=> 54, "name"=> "Cruze", "slug"=> "cruze"],
["brands_id"=> 54, "name"=> "Epica", "slug"=> "epica"],
["brands_id"=> 54, "name"=> "Lacetti", "slug"=> "lacetti"],
["brands_id"=> 54, "name"=> "Malibu", "slug"=> "malibu"],
["brands_id"=> 54, "name"=> "Niva", "slug"=> "niva"],
["brands_id"=> 54, "name"=> "Orlando", "slug"=> "orlando"],
["brands_id"=> 54, "name"=> "Trax", "slug"=> "trax"],
["brands_id"=> 54, "name"=> "Volt", "slug"=> "volt"],
["brands_id"=> 54, "name"=> "Alero", "slug"=> "alero"],
["brands_id"=> 54, "name"=> "Apache", "slug"=> "apache"],
["brands_id"=> 54, "name"=> "Astra", "slug"=> "astra"],
["brands_id"=> 54, "name"=> "Astro", "slug"=> "astro"],
["brands_id"=> 54, "name"=> "Avalanche", "slug"=> "avalanche"],
["brands_id"=> 54, "name"=> "Bel Air", "slug"=> "bel-air"],
["brands_id"=> 54, "name"=> "Beretta", "slug"=> "beretta"],
["brands_id"=> 54, "name"=> "Blazer", "slug"=> "blazer"],
["brands_id"=> 54, "name"=> "Blazer K5", "slug"=> "blazer-k5"],
["brands_id"=> 54, "name"=> "Bolt", "slug"=> "bolt"],
["brands_id"=> 54, "name"=> "C-10", "slug"=> "c-10"],
["brands_id"=> 54, "name"=> "Caprice", "slug"=> "caprice"],
["brands_id"=> 54, "name"=> "Cavalier", "slug"=> "cavalier"],
["brands_id"=> 54, "name"=> "Celebrity", "slug"=> "celebrity"],
["brands_id"=> 54, "name"=> "Celta", "slug"=> "celta"],
["brands_id"=> 54, "name"=> "Chevelle", "slug"=> "chevelle"],
["brands_id"=> 54, "name"=> "Chevette", "slug"=> "chevette"],
["brands_id"=> 54, "name"=> "Citation", "slug"=> "citation"],
["brands_id"=> 54, "name"=> "C/K", "slug"=> "ck"],
["brands_id"=> 54, "name"=> "Classic", "slug"=> "classic"],
["brands_id"=> 54, "name"=> "Cobalt", "slug"=> "cobalt"],
["brands_id"=> 54, "name"=> "Colorado", "slug"=> "colorado"],
["brands_id"=> 54, "name"=> "Corsa", "slug"=> "corsa"],
["brands_id"=> 54, "name"=> "Corsica", "slug"=> "corsica"],
["brands_id"=> 54, "name"=> "Corvair", "slug"=> "corvair"],
["brands_id"=> 54, "name"=> "Cruze (HR)", "slug"=> "cruze-hr"],
["brands_id"=> 54, "name"=> "CSV CR8", "slug"=> "csv-cr8"],
["brands_id"=> 54, "name"=> "Damas", "slug"=> "damas-"],
["brands_id"=> 54, "name"=> "Deluxe", "slug"=> "deluxe"],
["brands_id"=> 54, "name"=> "El Camino", "slug"=> "el-camino"],
["brands_id"=> 54, "name"=> "Equinox", "slug"=> "equinox"],
["brands_id"=> 54, "name"=> "Evanda", "slug"=> "evanda"],
["brands_id"=> 54, "name"=> "Express", "slug"=> "express"],
["brands_id"=> 54, "name"=> "Fleetmaster", "slug"=> "fleetmaster"],
["brands_id"=> 54, "name"=> "HHR", "slug"=> "hhr"],
["brands_id"=> 54, "name"=> "Impala", "slug"=> "impala"],
["brands_id"=> 54, "name"=> "Kalos", "slug"=> "kalos"],
["brands_id"=> 54, "name"=> "Lanos", "slug"=> "lanos"],
["brands_id"=> 54, "name"=> "Lumina", "slug"=> "lumina"],
["brands_id"=> 54, "name"=> "Lumina APV", "slug"=> "lumina-apv"],
["brands_id"=> 54, "name"=> "LUV D-MAX", "slug"=> "luv-d-max"],
["brands_id"=> 54, "name"=> "Master", "slug"=> "master"],
["brands_id"=> 54, "name"=> "Matiz", "slug"=> "matiz"],
["brands_id"=> 54, "name"=> "Menlo", "slug"=> "menlo"],
["brands_id"=> 54, "name"=> "Metro", "slug"=> "metro"],
["brands_id"=> 54, "name"=> "Monte Carlo", "slug"=> "monte-carlo"],
["brands_id"=> 54, "name"=> "Monza", "slug"=> "monza"],
["brands_id"=> 54, "name"=> "MW", "slug"=> "mw"],
["brands_id"=> 54, "name"=> "Nexia", "slug"=> "nexia-"],
["brands_id"=> 54, "name"=> "Nova", "slug"=> "nova"],
["brands_id"=> 54, "name"=> "Nubira", "slug"=> "nubira"],
["brands_id"=> 54, "name"=> "Omega", "slug"=> "omega"],
["brands_id"=> 54, "name"=> "Prizm", "slug"=> "prizm"],
["brands_id"=> 54, "name"=> "Rezzo", "slug"=> "rezzo"],
["brands_id"=> 54, "name"=> "S-10 Pickup", "slug"=> "s-10-pickup"],
["brands_id"=> 54, "name"=> "Sail", "slug"=> "sail"],
["brands_id"=> 54, "name"=> "Silverado", "slug"=> "silverado"],
["brands_id"=> 54, "name"=> "Sonic", "slug"=> "sonic"],
["brands_id"=> 54, "name"=> "Spark", "slug"=> "spark"],
["brands_id"=> 54, "name"=> "Special DeLuxe", "slug"=> "special-deluxe"],
["brands_id"=> 54, "name"=> "Spin", "slug"=> "spin"],
["brands_id"=> 54, "name"=> "SS", "slug"=> "ss"],
["brands_id"=> 54, "name"=> "SSR", "slug"=> "ssr"],
["brands_id"=> 54, "name"=> "Starcraft", "slug"=> "starcraft"],
["brands_id"=> 54, "name"=> "Suburban", "slug"=> "suburban"],
["brands_id"=> 54, "name"=> "Tacuma", "slug"=> "tacuma"],
["brands_id"=> 54, "name"=> "Tahoe", "slug"=> "tahoe"],
["brands_id"=> 54, "name"=> "Tavera", "slug"=> "tavera"],
["brands_id"=> 54, "name"=> "Tracker", "slug"=> "tracker"],
["brands_id"=> 54, "name"=> "TrailBlazer", "slug"=> "trailblazer"],
["brands_id"=> 54, "name"=> "Trans Sport", "slug"=> "trans-sport"],
["brands_id"=> 54, "name"=> "Traverse", "slug"=> "traverse"],
["brands_id"=> 54, "name"=> "Uplander", "slug"=> "uplander"],
["brands_id"=> 54, "name"=> "Van", "slug"=> "van"],
["brands_id"=> 54, "name"=> "Vectra", "slug"=> "vectra"],
["brands_id"=> 54, "name"=> "Venture", "slug"=> "venture"],
["brands_id"=> 54, "name"=> "Viva", "slug"=> "viva"],
["brands_id"=> 54, "name"=> "Zafira", "slug"=> "zafira"],

["brands_id"=> 55, "name"=> "200", "slug"=> "200"],
["brands_id"=> 55, "name"=> "300", "slug"=> "300"],
["brands_id"=> 55, "name"=> "300C", "slug"=> "300c"],
["brands_id"=> 55, "name"=> "Concorde", "slug"=> "concorde"],
["brands_id"=> 55, "name"=> "Crossfire", "slug"=> "crossfire"],
["brands_id"=> 55, "name"=> "Neon", "slug"=> "neon"],
["brands_id"=> 55, "name"=> "PT Cruiser", "slug"=> "pt-cruiser"],
["brands_id"=> 55, "name"=> "180", "slug"=> "180"],
["brands_id"=> 55, "name"=> "300 Letter Series", "slug"=> "300-letter-series"],
["brands_id"=> 55, "name"=> "300M", "slug"=> "300m"],
["brands_id"=> 55, "name"=> "Aspen", "slug"=> "aspen"],
["brands_id"=> 55, "name"=> "Cirrus", "slug"=> "cirrus"],
["brands_id"=> 55, "name"=> "Cordoba", "slug"=> "cordoba"],
["brands_id"=> 55, "name"=> "Daytona", "slug"=> "daytona"],
["brands_id"=> 55, "name"=> "Dynasty", "slug"=> "dynasty"],
["brands_id"=> 55, "name"=> "ES", "slug"=> "es"],
["brands_id"=> 55, "name"=> "Fifth Avenue", "slug"=> "fifth-avenue"],
["brands_id"=> 55, "name"=> "Imperial", "slug"=> "imperial"],
["brands_id"=> 55, "name"=> "Imperial Crown", "slug"=> "imperial-crown"],
["brands_id"=> 55, "name"=> "Intrepparent_id", "slug"=> "intrepparent_id"],
["brands_id"=> 55, "name"=> "LeBaron", "slug"=> "lebaron"],
["brands_id"=> 55, "name"=> "LHS", "slug"=> "lhs"],
["brands_id"=> 55, "name"=> "Nassau", "slug"=> "nassau"],
["brands_id"=> 55, "name"=> "Newport", "slug"=> "newport"],
["brands_id"=> 55, "name"=> "New Yorker", "slug"=> "new-yorker"],
["brands_id"=> 55, "name"=> "Pacifica", "slug"=> "pacifica"],
["brands_id"=> 55, "name"=> "Prowler", "slug"=> "prowler"],
["brands_id"=> 55, "name"=> "Saratoga", "slug"=> "saratoga"],
["brands_id"=> 55, "name"=> "Sebring", "slug"=> "sebring"],
["brands_id"=> 55, "name"=> "Stratus", "slug"=> "stratus"],
["brands_id"=> 55, "name"=> "TC by Maserati", "slug"=> "tc-by-maserati"],
["brands_id"=> 55, "name"=> "Town & Country", "slug"=> "town-country"],
["brands_id"=> 55, "name"=> "Turbine", "slug"=> "turbine"],
["brands_id"=> 55, "name"=> "Viper", "slug"=> "viper"],
["brands_id"=> 55, "name"=> "Vision", "slug"=> "vision"],
["brands_id"=> 55, "name"=> "Voyager", "slug"=> "voyager"],
["brands_id"=> 55, "name"=> "Windsor", "slug"=> "windsor"],


["brands_id"=> 56, "name"=> "Berlingo", "slug"=> "berlingo"],
["brands_id"=> 56, "name"=> "C3", "slug"=> "c3"],
["brands_id"=> 56, "name"=> "C3 Picasso", "slug"=> "c3-picasso"],
["brands_id"=> 56, "name"=> "C4", "slug"=> "c4"],
["brands_id"=> 56, "name"=> "C5", "slug"=> "c5"],
["brands_id"=> 56, "name"=> "C-Elysee", "slug"=> "c-elysee"],
["brands_id"=> 56, "name"=> "DS4", "slug"=> "ds4"],
["brands_id"=> 56, "name"=> "DS5", "slug"=> "ds5"],
["brands_id"=> 56, "name"=> "Xsara Picasso", "slug"=> "xsara-picasso"],
["brands_id"=> 56, "name"=> "2 CV", "slug"=> "2-cv"],
["brands_id"=> 56, "name"=> "AMI", "slug"=> "ami"],
["brands_id"=> 56, "name"=> "Ami EV", "slug"=> "ami-ev"],
["brands_id"=> 56, "name"=> "AX", "slug"=> "ax"],
["brands_id"=> 56, "name"=> "BX", "slug"=> "bx"],
["brands_id"=> 56, "name"=> "C1", "slug"=> "c1"],
["brands_id"=> 56, "name"=> "C2", "slug"=> "c2"],
["brands_id"=> 56, "name"=> "C3 Aircross", "slug"=> "c3-aircross"],
["brands_id"=> 56, "name"=> "C3 XR", "slug"=> "c3-xr"],
["brands_id"=> 56, "name"=> "C4 Aircross", "slug"=> "c4-aircross"],
["brands_id"=> 56, "name"=> "C4 Cactus", "slug"=> "c4-cactus"],
["brands_id"=> 56, "name"=> "C4 Picasso", "slug"=> "c4-picasso"],
["brands_id"=> 56, "name"=> "C4 SpaceTourer", "slug"=> "c4-spacetourer"],
["brands_id"=> 56, "name"=> "C5 Aircross", "slug"=> "c5-aircross"],
["brands_id"=> 56, "name"=> "C6", "slug"=> "c6"],
["brands_id"=> 56, "name"=> "C8", "slug"=> "c8"],
["brands_id"=> 56, "name"=> "C-Crosser", "slug"=> "c-crosser"],
["brands_id"=> 56, "name"=> "C-Quatre", "slug"=> "c-quatre"],
["brands_id"=> 56, "name"=> "C-Triomphe", "slug"=> "c-triomphe"],
["brands_id"=> 56, "name"=> "CX", "slug"=> "cx"],
["brands_id"=> 56, "name"=> "C-Zero", "slug"=> "c-zero"],
["brands_id"=> 56, "name"=> "DS", "slug"=> "ds"],
["brands_id"=> 56, "name"=> "DS3", "slug"=> "ds3"],
["brands_id"=> 56, "name"=> "Dyane", "slug"=> "dyane"],
["brands_id"=> 56, "name"=> "E-Mehari", "slug"=> "e-mehari"],
["brands_id"=> 56, "name"=> "Evasion", "slug"=> "evasion"],
["brands_id"=> 56, "name"=> "GS", "slug"=> "gs"],
["brands_id"=> 56, "name"=> "Jumper", "slug"=> "jumper"],
["brands_id"=> 56, "name"=> "Jumpy", "slug"=> "jumpy"],
["brands_id"=> 56, "name"=> "LN / LNA", "slug"=> "ln-lna"],
["brands_id"=> 56, "name"=> "Nemo", "slug"=> "nemo"],
["brands_id"=> 56, "name"=> "Saxo", "slug"=> "saxo"],
["brands_id"=> 56, "name"=> "SM", "slug"=> "sm"],
["brands_id"=> 56, "name"=> "SpaceTourer", "slug"=> "spacetourer"],
["brands_id"=> 56, "name"=> "Traction Avant", "slug"=> "traction-avant"],
["brands_id"=> 56, "name"=> "Visa", "slug"=> "visa"],
["brands_id"=> 56, "name"=> "Xantia", "slug"=> "xantia"],
["brands_id"=> 56, "name"=> "XM", "slug"=> "xm"],
["brands_id"=> 56, "name"=> "Xsara", "slug"=> "xsara"],
["brands_id"=> 56, "name"=> "ZX", "slug"=> "zx"],

["brands_id"=> 57, "name"=> "V16t", "slug"=> "v16t"],

["brands_id"=> 58, "name"=> "T Rex", "slug"=> "t-rex"],

["brands_id"=> 59, "name"=> "L-29", "slug"=> "l-29"],

["brands_id"=> 60, "name"=> "Ateca", "slug"=> "ateca"],
["brands_id"=> 60, "name"=> "Born", "slug"=> "born"],
["brands_id"=> 60, "name"=> "Formentor", "slug"=> "formentor"],
["brands_id"=> 60, "name"=> "Leon", "slug"=> "leon-"],

["brands_id"=> 61, "name"=> "Dokker", "slug"=> "dokker"],
["brands_id"=> 61, "name"=> "Duster", "slug"=> "duster"],
["brands_id"=> 61, "name"=> "Lodgy", "slug"=> "lodgy"],
["brands_id"=> 61, "name"=> "Logan", "slug"=> "logan"],
["brands_id"=> 61, "name"=> "Sandero", "slug"=> "sandero"],
["brands_id"=> 61, "name"=> "1300", "slug"=> "1300"],
["brands_id"=> 61, "name"=> "1310", "slug"=> "1310"],
["brands_id"=> 61, "name"=> "1320", "slug"=> "1320"],
["brands_id"=> 61, "name"=> "1325", "slug"=> "1325"],
["brands_id"=> 61, "name"=> "1410", "slug"=> "1410"],
["brands_id"=> 61, "name"=> "Nova", "slug"=> "nova"],
["brands_id"=> 61, "name"=> "Pick-Up", "slug"=> "pick-up"],
["brands_id"=> 61, "name"=> "Solenza", "slug"=> "solenza"],
["brands_id"=> 61, "name"=> "Spring", "slug"=> "spring"],
["brands_id"=> 61, "name"=> "SuperNova", "slug"=> "supernova"],

["brands_id"=> 62, "name"=> "City Leading", "slug"=> "city-leading"],
["brands_id"=> 62, "name"=> "Shuttle", "slug"=> "shuttle"],
["brands_id"=> 62, "name"=> "Smoothing", "slug"=> "smoothing"],


["brands_id"=> 63, "name"=> "Damas", "slug"=> "damas"],
["brands_id"=> 63, "name"=> "Espero", "slug"=> "espero"],
["brands_id"=> 63, "name"=> "Gentra", "slug"=> "gentra-"],
["brands_id"=> 63, "name"=> "Lanos", "slug"=> "lanos"],
["brands_id"=> 63, "name"=> "Leganza", "slug"=> "leganza"],
["brands_id"=> 63, "name"=> "Matiz", "slug"=> "matiz"],
["brands_id"=> 63, "name"=> "Nexia", "slug"=> "nexia"],
["brands_id"=> 63, "name"=> "Nubira", "slug"=> "nubira"],
["brands_id"=> 63, "name"=> "Racer", "slug"=> "racer"],
["brands_id"=> 63, "name"=> "Ace (Super Salon)", "slug"=> "ace"],
["brands_id"=> 63, "name"=> "Alpheon", "slug"=> "alpheon"],
["brands_id"=> 63, "name"=> "Arcadia", "slug"=> "arcadia"],
["brands_id"=> 63, "name"=> "BH 120", "slug"=> "bh-120"],
["brands_id"=> 63, "name"=> "BS 106", "slug"=> "bs-106"],
["brands_id"=> 63, "name"=> "Chairman", "slug"=> "chairman"],
["brands_id"=> 63, "name"=> "Evanda", "slug"=> "evanda"],
["brands_id"=> 63, "name"=> "G2X", "slug"=> "g2x"],
["brands_id"=> 63, "name"=> "Kalos", "slug"=> "kalos"],
["brands_id"=> 63, "name"=> "Korando", "slug"=> "korando"],
["brands_id"=> 63, "name"=> "Labo", "slug"=> "labo"],
["brands_id"=> 63, "name"=> "Lacetti", "slug"=> "lacetti-"],
["brands_id"=> 63, "name"=> "Lacetti Premiere", "slug"=> "lacetti-premiere"],
["brands_id"=> 63, "name"=> "LeMans", "slug"=> "lemans"],
["brands_id"=> 63, "name"=> "Lublin 3", "slug"=> "lublin-3"],
["brands_id"=> 63, "name"=> "Magnus", "slug"=> "magnus"],
["brands_id"=> 63, "name"=> "Matiz Creative", "slug"=> "matiz-creative"],
["brands_id"=> 63, "name"=> "Musso", "slug"=> "musso"],
["brands_id"=> 63, "name"=> "Novus", "slug"=> "novus"],
["brands_id"=> 63, "name"=> "Prince", "slug"=> "prince"],
["brands_id"=> 63, "name"=> "Rezzo", "slug"=> "rezzo"],
["brands_id"=> 63, "name"=> "Royale", "slug"=> "royale"],
["brands_id"=> 63, "name"=> "Sens", "slug"=> "sens"],
["brands_id"=> 63, "name"=> "Tacuma", "slug"=> "tacuma"],
["brands_id"=> 63, "name"=> "Tico", "slug"=> "tico"],
["brands_id"=> 63, "name"=> "Tosca", "slug"=> "tosca"],
["brands_id"=> 63, "name"=> "Winstorm", "slug"=> "winstorm"],

["brands_id"=> 64, "name"=> "95", "slug"=> "95"],
["brands_id"=> 64, "name"=> "CF", "slug"=> "cf"],
["brands_id"=> 64, "name"=> "LF", "slug"=> "lf"],
["brands_id"=> 64, "name"=> "XF", "slug"=> "xf"],

["brands_id"=> 65, "name"=> "Cuore", "slug"=> "cuore"],
["brands_id"=> 65, "name"=> "Materia", "slug"=> "materia"],
["brands_id"=> 65, "name"=> "Altis", "slug"=> "altis"],
["brands_id"=> 65, "name"=> "Applause", "slug"=> "applause"],
["brands_id"=> 65, "name"=> "Atrai", "slug"=> "atrai"],
["brands_id"=> 65, "name"=> "Bee", "slug"=> "bee"],
["brands_id"=> 65, "name"=> "Be-go", "slug"=> "be-go"],
["brands_id"=> 65, "name"=> "Boon", "slug"=> "boon"],
["brands_id"=> 65, "name"=> "Boon Luminas", "slug"=> "boon-luminas"],
["brands_id"=> 65, "name"=> "Cast", "slug"=> "cast"],
["brands_id"=> 65, "name"=> "Ceria", "slug"=> "ceria"],
["brands_id"=> 65, "name"=> "Charade", "slug"=> "charade"],
["brands_id"=> 65, "name"=> "Charmant", "slug"=> "charmant"],
["brands_id"=> 65, "name"=> "Coo", "slug"=> "coo"],
["brands_id"=> 65, "name"=> "Copen", "slug"=> "copen"],
["brands_id"=> 65, "name"=> "Delta Wagon", "slug"=> "delta-wagon"],
["brands_id"=> 65, "name"=> "Esse", "slug"=> "esse"],
["brands_id"=> 65, "name"=> "Fellow", "slug"=> "fellow"],
["brands_id"=> 65, "name"=> "Feroza", "slug"=> "feroza"],
["brands_id"=> 65, "name"=> "Gran Max", "slug"=> "gran-max"],
["brands_id"=> 65, "name"=> "Gran Move", "slug"=> "gran-move"],
["brands_id"=> 65, "name"=> "Hijet", "slug"=> "hijet"],
["brands_id"=> 65, "name"=> "Leeza", "slug"=> "leeza"],
["brands_id"=> 65, "name"=> "MAX", "slug"=> "max"],
["brands_id"=> 65, "name"=> "Mebius", "slug"=> "mebius"],
["brands_id"=> 65, "name"=> "Mparent_idget", "slug"=> "mparent_idget"],
["brands_id"=> 65, "name"=> "Mira", "slug"=> "mira"],
["brands_id"=> 65, "name"=> "Mira e=>S", "slug"=> "mira-es"],
["brands_id"=> 65, "name"=> "Mira Gino", "slug"=> "mira-gino"],
["brands_id"=> 65, "name"=> "Move", "slug"=> "move"],
["brands_id"=> 65, "name"=> "Move Canbus", "slug"=> "move-canbus"],
["brands_id"=> 65, "name"=> "Move Conte", "slug"=> "move-conte"],
["brands_id"=> 65, "name"=> "Move Latte", "slug"=> "move-latte"],
["brands_id"=> 65, "name"=> "Naked", "slug"=> "naked"],
["brands_id"=> 65, "name"=> "Opti", "slug"=> "opti"],
["brands_id"=> 65, "name"=> "Pyzar", "slug"=> "pyzar"],
["brands_id"=> 65, "name"=> "Rocky", "slug"=> "rocky"],
["brands_id"=> 65, "name"=> "Rugger", "slug"=> "rugger"],
["brands_id"=> 65, "name"=> "Sirion", "slug"=> "sirion"],
["brands_id"=> 65, "name"=> "Sonica", "slug"=> "sonica"],
["brands_id"=> 65, "name"=> "Storia", "slug"=> "storia"],
["brands_id"=> 65, "name"=> "Taft", "slug"=> "taft"],
["brands_id"=> 65, "name"=> "Tanto", "slug"=> "tanto"],
["brands_id"=> 65, "name"=> "Tanto Exe", "slug"=> "tanto-exe"],
["brands_id"=> 65, "name"=> "Terios", "slug"=> "terios"],
["brands_id"=> 65, "name"=> "Thor", "slug"=> "thor"],
["brands_id"=> 65, "name"=> "Trevis", "slug"=> "trevis"],
["brands_id"=> 65, "name"=> "Wake", "slug"=> "wake"],
["brands_id"=> 65, "name"=> "Wildcat", "slug"=> "wildcat"],
["brands_id"=> 65, "name"=> "Xenia", "slug"=> "xenia"],
["brands_id"=> 65, "name"=> "YRV", "slug"=> "yrv"],


["brands_id"=> 66, "name"=> "DS420", "slug"=> "ds420"],
["brands_id"=> 66, "name"=> "SP250", "slug"=> "sp250"],
["brands_id"=> 66, "name"=> "X300", "slug"=> "x300"],
["brands_id"=> 66, "name"=> "X350", "slug"=> "x350"],
["brands_id"=> 66, "name"=> "XJS", "slug"=> "xjs"],
["brands_id"=> 66, "name"=> "Sovereign (XJ6)", "slug"=> "sovereign-xj6"],
["brands_id"=> 66, "name"=> "X308", "slug"=> "x308"],
["brands_id"=> 66, "name"=> "XJ40", "slug"=> "xj40"],

["brands_id"=> 67, "name"=> "Stradale", "slug"=> "stradale"],


["brands_id"=> 68, "name"=> "240Z", "slug"=> "240z"],
["brands_id"=> 68, "name"=> "280ZX", "slug"=> "280zx"],
["brands_id"=> 68, "name"=> "Bluebird", "slug"=> "bluebird"],
["brands_id"=> 68, "name"=> "on-DO", "slug"=> "on-do"],
["brands_id"=> 68, "name"=> "Sunny", "slug"=> "sunny-"],
["brands_id"=> 68, "name"=> "720", "slug"=> "720"],
["brands_id"=> 68, "name"=> "Cherry", "slug"=> "cherry"],
["brands_id"=> 68, "name"=> "GO", "slug"=> "go"],
["brands_id"=> 68, "name"=> "GO+", "slug"=> "go"],
["brands_id"=> 68, "name"=> "Laurel", "slug"=> "laurel"],
["brands_id"=> 68, "name"=> "mi-DO", "slug"=> "mi-do"],
["brands_id"=> 68, "name"=> "Stanza", "slug"=> "stanza"],
["brands_id"=> 68, "name"=> "Urvan", "slug"=> "urvan"],
["brands_id"=> 68, "name"=> "Violet", "slug"=> "violet"],

["brands_id"=> 69, "name"=> "D6", "slug"=> "d6"],

["brands_id"=> 70, "name"=> "DMC-12", "slug"=> "dmc-12"],

["brands_id"=> 71, "name"=> "Antelope", "slug"=> "antelope"],
["brands_id"=> 71, "name"=> "Aurora", "slug"=> "aurora"],
["brands_id"=> 71, "name"=> "Saladin", "slug"=> "saladin"],
["brands_id"=> 71, "name"=> "Shuttle", "slug"=> "shuttle"],
["brands_id"=> 71, "name"=> "Cowboy", "slug"=> "cowboy"],
["brands_id"=> 71, "name"=> "Land Crown", "slug"=> "land-crown"],
["brands_id"=> 71, "name"=> "Plutus", "slug"=> "plutus"],


["brands_id"=> 72, "name"=> "Custom", "slug"=> "custom"],
["brands_id"=> 72, "name"=> "Firedome", "slug"=> "firedome"],
["brands_id"=> 72, "name"=> "Fireflite", "slug"=> "fireflite"],

["brands_id"=> 73, "name"=> "Guara", "slug"=> "guara"],
["brands_id"=> 73, "name"=> "Mangusta", "slug"=> "mangusta"],
["brands_id"=> 73, "name"=> "Pantera", "slug"=> "pantera"],
["brands_id"=> 73, "name"=> "Bigua", "slug"=> "bigua"],
["brands_id"=> 73, "name"=> "Longchamp", "slug"=> "longchamp"],
["brands_id"=> 73, "name"=> "Vallelunga", "slug"=> "vallelunga"],

["brands_id"=> 75, "name"=> "Glory 330", "slug"=> "glory-330"],
["brands_id"=> 75, "name"=> "Glory 330s", "slug"=> "glory-330s"],

["brands_id"=> 76, "name"=> "3=6", "slug"=> "36"]
];

