$models2 = [
["parent_id"=> 78, "name"=> "Caliber",  "slug"=> "caliber"],
["parent_id"=> 78, "name"=> "Challenger",  "slug"=> "challenger"],
["parent_id"=> 78, "name"=> "Charger",  "slug"=> "charger"],
["parent_id"=> 78, "name"=> "Durango",  "slug"=> "durango"],
["parent_id"=> 78, "name"=> "Intrepid",  "slug"=> "intrepid"],
["parent_id"=> 78, "name"=> "Journey",  "slug"=> "journey"],
["parent_id"=> 78, "name"=> "Nitro",  "slug"=> "nitro"],
["parent_id"=> 78, "name"=> "600",  "slug"=> "600"],
["parent_id"=> 78, "name"=> "Aries",  "slug"=> "aries"],
["parent_id"=> 78, "name"=> "Avenger",  "slug"=> "avenger"],
["parent_id"=> 78, "name"=> "Caravan",  "slug"=> "caravan"],
["parent_id"=> 78, "name"=> "Charger Daytona",  "slug"=> "charger-daytona"],
["parent_id"=> 78, "name"=> "Colt",  "slug"=> "colt"],
["parent_id"=> 78, "name"=> "Custom Royal",  "slug"=> "custom-royal"],
["parent_id"=> 78, "name"=> "D8",  "slug"=> "d8"],
["parent_id"=> 78, "name"=> "Dakota",  "slug"=> "dakota"],
["parent_id"=> 78, "name"=> "Dart",  "slug"=> "dart"],
["parent_id"=> 78, "name"=> "Daytona",  "slug"=> "daytona"],
["parent_id"=> 78, "name"=> "Diplomat",  "slug"=> "diplomat"],
["parent_id"=> 78, "name"=> "D/W Series",  "slug"=> "dw-series"],
["parent_id"=> 78, "name"=> "Dynasty",  "slug"=> "dynasty"],
["parent_id"=> 78, "name"=> "Lancer",  "slug"=> "lancer"],
["parent_id"=> 78, "name"=> "Magnum",  "slug"=> "magnum"],
["parent_id"=> 78, "name"=> "Mayfair",  "slug"=> "mayfair"],
["parent_id"=> 78, "name"=> "Monaco",  "slug"=> "monaco"],
["parent_id"=> 78, "name"=> "Neon",  "slug"=> "neon"],
["parent_id"=> 78, "name"=> "Omni",  "slug"=> "omni"],
["parent_id"=> 78, "name"=> "Raider",  "slug"=> "raider"],
["parent_id"=> 78, "name"=> "RAM",  "slug"=> "ram"],
["parent_id"=> 78, "name"=> "Ramcharger",  "slug"=> "ramcharger"],
["parent_id"=> 78, "name"=> "Ram Van",  "slug"=> "ram-van"],
["parent_id"=> 78, "name"=> "Shadow",  "slug"=> "shadow"],
["parent_id"=> 78, "name"=> "Spirit",  "slug"=> "spirit"],
["parent_id"=> 78, "name"=> "Stealth",  "slug"=> "stealth"],
["parent_id"=> 78, "name"=> "Stratus",  "slug"=> "stratus"],
["parent_id"=> 78, "name"=> "Viper",  "slug"=> "viper"],
["parent_id"=> 78, "name"=> "WC series",  "slug"=> "wc-series"],
["parent_id"=> 79, "name"=> "H30 Cross",  "slug"=> "h30-cross"],
["parent_id"=> 79, "name"=> "S30",  "slug"=> "s30"],
["parent_id"=> 79, "name"=> "370",  "slug"=> "370"],
["parent_id"=> 79, "name"=> "580",  "slug"=> "580"],
["parent_id"=> 79, "name"=> "A30",  "slug"=> "a30"],
["parent_id"=> 79, "name"=> "A9",  "slug"=> "a9"],
["parent_id"=> 79, "name"=> "AX4",  "slug"=> "ax4"],
["parent_id"=> 79, "name"=> "AX7",  "slug"=> "ax7"],
["parent_id"=> 79, "name"=> "Captain-T",  "slug"=> "captain-t"],
["parent_id"=> 79, "name"=> "DFA",  "slug"=> "dfa"],
["parent_id"=> 79, "name"=> "DFL",  "slug"=> "dfl"],
["parent_id"=> 79, "name"=> "E70 (Fengshen)",  "slug"=> "e70"],
["parent_id"=> 79, "name"=> "MPV",  "slug"=> "mpv"],
["parent_id"=> 79, "name"=> "Oting",  "slug"=> "oting"],
["parent_id"=> 79, "name"=> "Rich",  "slug"=> "rich"],
["parent_id"=> 79, "name"=> "Rich 6",  "slug"=> "rich-6"],
["parent_id"=> 79, "name"=> "Sokon",  "slug"=> "sokon"],
["parent_id"=> 79, "name"=> "T5 Evo",  "slug"=> "t5-evo"],
["parent_id"=> 79, "name"=> "Xuan EV",  "slug"=> "xuan-ev"],
["parent_id"=> 80, "name"=> "Assol",  "slug"=> "assol"],
["parent_id"=> 80, "name"=> "Kondor",  "slug"=> "kondor"],
["parent_id"=> 80, "name"=> "Orion",  "slug"=> "orion"],
["parent_id"=> 81, "name"=> "D8",  "slug"=> "d8"],
["parent_id"=> 81, "name"=> "D8 GTO",  "slug"=> "d8-gto"],
["parent_id"=> 81, "name"=> "D8 Cosworth",  "slug"=> "d8-cosworth"],
["parent_id"=> 81, "name"=> "D8 GT",  "slug"=> "d8-gt"],
["parent_id"=> 81, "name"=> "D8 Zetec",  "slug"=> "d8-zetec"],
["parent_id"=> 82, "name"=> "3",  "slug"=> "3"],
["parent_id"=> 82, "name"=> "4",  "slug"=> "4"],
["parent_id"=> 82, "name"=> "5",  "slug"=> "5"],
["parent_id"=> 82, "name"=> "7 Crossback",  "slug"=> "7-crossback"],
["parent_id"=> 82, "name"=> "3 Crossback",  "slug"=> "3-crossback"],
["parent_id"=> 82, "name"=> "9",  "slug"=> "9"],
["parent_id"=> 83, "name"=> "H3",  "slug"=> "h3"],
["parent_id"=> 83, "name"=> "H5",  "slug"=> "h5"],
["parent_id"=> 84, "name"=> "Premier",  "slug"=> "premier"],
["parent_id"=> 84, "name"=> "Summit",  "slug"=> "summit"],
["parent_id"=> 84, "name"=> "Talon",  "slug"=> "talon"],
["parent_id"=> 84, "name"=> "Vision",  "slug"=> "vision"],
["parent_id"=> 84, "name"=> "Vista",  "slug"=> "vista"],
["parent_id"=> 85, "name"=> "SS",  "slug"=> "ss"],
["parent_id"=> 86, "name"=> "Series IV",  "slug"=> "series-iv"],
["parent_id"=> 86, "name"=> "Series V",  "slug"=> "series-v"],
["parent_id"=> 87, "name"=> "LX",  "slug"=> "lx"],
["parent_id"=> 87, "name"=> "TXL",  "slug"=> "txl"],
["parent_id"=> 87, "name"=> "VX",  "slug"=> "vx"],
["parent_id"=> 88, "name"=> "Future FF 91",  "slug"=> "future-ff-91"],
["parent_id"=> 89, "name"=> "Besturn B30",  "slug"=> "besturn-b30"],
["parent_id"=> 89, "name"=> "Besturn X40",  "slug"=> "besturn-x40"],
["parent_id"=> 89, "name"=> "Besturn X80",  "slug"=> "besturn-x80"],
["parent_id"=> 89, "name"=> "V2",  "slug"=> "v2"],
["parent_id"=> 89, "name"=> "V5",  "slug"=> "v5"],
["parent_id"=> 89, "name"=> "1041",  "slug"=> "1041"],
["parent_id"=> 89, "name"=> "6350",  "slug"=> "6350"],
["parent_id"=> 89, "name"=> "6371",  "slug"=> "6371"],
["parent_id"=> 89, "name"=> "Besturn B50",  "slug"=> "besturn-b50"],
["parent_id"=> 89, "name"=> "Besturn B70",  "slug"=> "besturn-b70"],
["parent_id"=> 89, "name"=> "Besturn E01",  "slug"=> "besturn-e01"],
["parent_id"=> 89, "name"=> "J5",  "slug"=> "j5"],
["parent_id"=> 89, "name"=> "J6",  "slug"=> "j6"],
["parent_id"=> 89, "name"=> "Jinn",  "slug"=> "jinn"],
["parent_id"=> 89, "name"=> "Junpai D60",  "slug"=> "junpai-d60"],
["parent_id"=> 89, "name"=> "Oley",  "slug"=> "oley"],
["parent_id"=> 89, "name"=> "Vita",  "slug"=> "vita"],
["parent_id"=> 90, "name"=> "California",  "slug"=> "california"],
["parent_id"=> 90, "name"=> "F12berlinetta",  "slug"=> "f12berlinetta"],
["parent_id"=> 90, "name"=> "F430",  "slug"=> "f430"],
["parent_id"=> 90, "name"=> "FF",  "slug"=> "ff"],
["parent_id"=> 90, "name"=> "FXX K",  "slug"=> "fxx-k"],
["parent_id"=> 90, "name"=> "250 GTO",  "slug"=> "250-gto"],
["parent_id"=> 90, "name"=> "296",  "slug"=> "296"],
["parent_id"=> 90, "name"=> "328",  "slug"=> "328"],
["parent_id"=> 90, "name"=> "348",  "slug"=> "348"],
["parent_id"=> 90, "name"=> "360",  "slug"=> "360"],
["parent_id"=> 90, "name"=> "400",  "slug"=> "400"],
["parent_id"=> 90, "name"=> "412",  "slug"=> "412"],
["parent_id"=> 90, "name"=> "456",  "slug"=> "456"],
["parent_id"=> 90, "name"=> "458",  "slug"=> "458"],
["parent_id"=> 90, "name"=> "488",  "slug"=> "488"],
["parent_id"=> 90, "name"=> "512 BB",  "slug"=> "512-bb"],
["parent_id"=> 90, "name"=> "512 M",  "slug"=> "512-m"],
["parent_id"=> 90, "name"=> "512 TR",  "slug"=> "512-tr"],
["parent_id"=> 90, "name"=> "550",  "slug"=> "550"],
["parent_id"=> 90, "name"=> "575M",  "slug"=> "575m"],
["parent_id"=> 90, "name"=> "599",  "slug"=> "599"],
["parent_id"=> 90, "name"=> "612",  "slug"=> "612"],
["parent_id"=> 90, "name"=> "812",  "slug"=> "812"],
["parent_id"=> 90, "name"=> "Dino 206 GT",  "slug"=> "dino-206-gt"],
["parent_id"=> 90, "name"=> "Dino 208/308 GT4",  "slug"=> "dino-208308-gt4"],
["parent_id"=> 90, "name"=> "Dino 246 GT",  "slug"=> "dino-246-gt"],
["parent_id"=> 90, "name"=> "Enzo",  "slug"=> "enzo"],
["parent_id"=> 90, "name"=> "F355",  "slug"=> "f355"],
["parent_id"=> 90, "name"=> "F40",  "slug"=> "f40"],
["parent_id"=> 90, "name"=> "F50",  "slug"=> "f50"],
["parent_id"=> 90, "name"=> "F8",  "slug"=> "f8"],
["parent_id"=> 90, "name"=> "GTC4Lusso",  "slug"=> "gtc4lusso"],
["parent_id"=> 90, "name"=> "LaFerrari",  "slug"=> "laferrari"],
["parent_id"=> 90, "name"=> "Mondial",  "slug"=> "mondial"],
["parent_id"=> 90, "name"=> "Monza SP",  "slug"=> "monza-sp"],
["parent_id"=> 90, "name"=> "Portofino",  "slug"=> "portofino"],
["parent_id"=> 90, "name"=> "Purosangue",  "slug"=> "purosangue"],
["parent_id"=> 90, "name"=> "Roma",  "slug"=> "roma"],
["parent_id"=> 90, "name"=> "SF90",  "slug"=> "sf90"],
["parent_id"=> 90, "name"=> "Testarossa",  "slug"=> "testarossa"],
["parent_id"=> 91, "name"=> "500L",  "slug"=> "500l"],
["parent_id"=> 91, "name"=> "Albea",  "slug"=> "albea"],
["parent_id"=> 91, "name"=> "Cinquecento",  "slug"=> "cinquecento"],
["parent_id"=> 91, "name"=> "Doblo",  "slug"=> "doblo"],
["parent_id"=> 91, "name"=> "Fiorino",  "slug"=> "fiorino"],
["parent_id"=> 91, "name"=> "Linea",  "slug"=> "linea"],
["parent_id"=> 91, "name"=> "Panda",  "slug"=> "panda"],
["parent_id"=> 91, "name"=> "Punto",  "slug"=> "punto"],
["parent_id"=> 91, "name"=> "Qubo",  "slug"=> "qubo"],
["parent_id"=> 91, "name"=> "124",  "slug"=> "124"],
["parent_id"=> 91, "name"=> "124 Spider",  "slug"=> "124-spider"],
["parent_id"=> 91, "name"=> "124 Sport Spider",  "slug"=> "124-sport-spider"],
["parent_id"=> 91, "name"=> "125",  "slug"=> "125"],
["parent_id"=> 91, "name"=> "126",  "slug"=> "126"],
["parent_id"=> 91, "name"=> "127",  "slug"=> "127"],
["parent_id"=> 91, "name"=> "128",  "slug"=> "128"],
["parent_id"=> 91, "name"=> "130",  "slug"=> "130"],
["parent_id"=> 91, "name"=> "131",  "slug"=> "131"],
["parent_id"=> 91, "name"=> "132",  "slug"=> "132"],
["parent_id"=> 91, "name"=> "238",  "slug"=> "238"],
["parent_id"=> 91, "name"=> "500",  "slug"=> "500"],
["parent_id"=> 91, "name"=> "500X",  "slug"=> "500x"],
["parent_id"=> 91, "name"=> "508",  "slug"=> "508"],
["parent_id"=> 91, "name"=> "600",  "slug"=> "600"],
["parent_id"=> 91, "name"=> "900T",  "slug"=> "900t"],
["parent_id"=> 91, "name"=> "Argenta",  "slug"=> "argenta"],
["parent_id"=> 91, "name"=> "Barchetta",  "slug"=> "barchetta"],
["parent_id"=> 91, "name"=> "Brava",  "slug"=> "brava"],
["parent_id"=> 91, "name"=> "Bravo",  "slug"=> "bravo"],
["parent_id"=> 91, "name"=> "Coupe",  "slug"=> "coupe"],
["parent_id"=> 91, "name"=> "Croma",  "slug"=> "croma"],
["parent_id"=> 91, "name"=> "Ducato",  "slug"=> "ducato"],
["parent_id"=> 91, "name"=> "Duna",  "slug"=> "duna"],
["parent_id"=> 91, "name"=> "Egea",  "slug"=> "egea"],
["parent_id"=> 91, "name"=> "Freemont",  "slug"=> "freemont"],
["parent_id"=> 91, "name"=> "Fullback",  "slug"=> "fullback"],
["parent_id"=> 91, "name"=> "Idea",  "slug"=> "idea"],
["parent_id"=> 91, "name"=> "Marea",  "slug"=> "marea"],
["parent_id"=> 91, "name"=> "Multipla",  "slug"=> "multipla"],
["parent_id"=> 91, "name"=> "Palio",  "slug"=> "palio"],
["parent_id"=> 91, "name"=> "Regata",  "slug"=> "regata"],
["parent_id"=> 91, "name"=> "Ritmo",  "slug"=> "ritmo"],
["parent_id"=> 91, "name"=> "Scudo",  "slug"=> "scudo"],
["parent_id"=> 91, "name"=> "Sedici",  "slug"=> "sedici"],
["parent_id"=> 91, "name"=> "Seicento",  "slug"=> "seicento"],
["parent_id"=> 91, "name"=> "Siena",  "slug"=> "siena"],
["parent_id"=> 91, "name"=> "Stilo",  "slug"=> "stilo"],
["parent_id"=> 91, "name"=> "Strada",  "slug"=> "strada"],
["parent_id"=> 91, "name"=> "Tempra",  "slug"=> "tempra"],
["parent_id"=> 91, "name"=> "Tipo",  "slug"=> "tipo"],
["parent_id"=> 91, "name"=> "Ulysse",  "slug"=> "ulysse"],
["parent_id"=> 91, "name"=> "Uno",  "slug"=> "uno"],
["parent_id"=> 91, "name"=> "X 1/9",  "slug"=> "x-19"],
["parent_id"=> 92, "name"=> "Karma",  "slug"=> "karma"],
["parent_id"=> 92, "name"=> "Ocean",  "slug"=> "ocean"],
["parent_id"=> 93, "name"=> "F",  "slug"=> "f"],
["parent_id"=> 94, "name"=> "Edge",  "slug"=> "edge"],
["parent_id"=> 94, "name"=> "Escape",  "slug"=> "escape"],
["parent_id"=> 94, "name"=> "Explorer",  "slug"=> "explorer"],
["parent_id"=> 94, "name"=> "Fiesta",  "slug"=> "fiesta"],
["parent_id"=> 94, "name"=> "Focus",  "slug"=> "focus"],
["parent_id"=> 94, "name"=> "Fusion",  "slug"=> "fusion"],
["parent_id"=> 94, "name"=> "Kuga",  "slug"=> "kuga"],
["parent_id"=> 94, "name"=> "Mondeo",  "slug"=> "mondeo"],
["parent_id"=> 94, "name"=> "Mustang",  "slug"=> "mustang"],
["parent_id"=> 94, "name"=> "Tourneo Connect",  "slug"=> "tourneo-connect"],
["parent_id"=> 94, "name"=> "Tourneo Custom",  "slug"=> "tourneo-custom"],
["parent_id"=> 94, "name"=> "Transit",  "slug"=> "transit"],
["parent_id"=> 94, "name"=> "Transit Custom",  "slug"=> "transit-custom"],
["parent_id"=> 94, "name"=> "Aerostar",  "slug"=> "aerostar"],
["parent_id"=> 94, "name"=> "Aspire",  "slug"=> "aspire"],
["parent_id"=> 94, "name"=> "B-MAX",  "slug"=> "b-max"],
["parent_id"=> 94, "name"=> "Bronco",  "slug"=> "bronco"],
["parent_id"=> 94, "name"=> "Bronco-II",  "slug"=> "bronco-ii"],
["parent_id"=> 94, "name"=> "Bronco Sport",  "slug"=> "bronco-sport"],
["parent_id"=> 94, "name"=> "Capri",  "slug"=> "capri"],
["parent_id"=> 94, "name"=> "Cargo",  "slug"=> "cargo"],
["parent_id"=> 94, "name"=> "C-MAX",  "slug"=> "c-max"],
["parent_id"=> 94, "name"=> "Consul",  "slug"=> "consul"],
["parent_id"=> 94, "name"=> "Contour",  "slug"=> "contour"],
["parent_id"=> 94, "name"=> "Cortina",  "slug"=> "cortina"],
["parent_id"=> 94, "name"=> "Cougar",  "slug"=> "cougar"],
["parent_id"=> 94, "name"=> "Courier",  "slug"=> "courier"],
["parent_id"=> 94, "name"=> "Crown Victoria",  "slug"=> "crown-victoria"],
["parent_id"=> 94, "name"=> "Custom",  "slug"=> "custom"],
["parent_id"=> 94, "name"=> "Econoline",  "slug"=> "econoline"],
["parent_id"=> 94, "name"=> "EcoSport",  "slug"=> "ecosport"],
["parent_id"=> 94, "name"=> "Equator",  "slug"=> "equator"],
["parent_id"=> 94, "name"=> "Escort",  "slug"=> "escort"],
["parent_id"=> 94, "name"=> "E-series",  "slug"=> "e-series"],
["parent_id"=> 94, "name"=> "Everest",  "slug"=> "everest"],
["parent_id"=> 94, "name"=> "Excursion",  "slug"=> "excursion"],
["parent_id"=> 94, "name"=> "Expedition",  "slug"=> "expedition"],
["parent_id"=> 94, "name"=> "Explorer Sport Trac",  "slug"=> "explorer-sport-trac"],
["parent_id"=> 94, "name"=> "F-150",  "slug"=> "f-150"],
["parent_id"=> 94, "name"=> "Fairlane",  "slug"=> "fairlane"],
["parent_id"=> 94, "name"=> "Fairmont",  "slug"=> "fairmont"],
["parent_id"=> 94, "name"=> "Falcon",  "slug"=> "falcon"],
["parent_id"=> 94, "name"=> "Festiva",  "slug"=> "festiva"],
["parent_id"=> 94, "name"=> "Fiesta ST",  "slug"=> "fiesta-st"],
["parent_id"=> 94, "name"=> "Five Hundred",  "slug"=> "five-hundred"],
["parent_id"=> 94, "name"=> "Flex",  "slug"=> "flex"],
["parent_id"=> 94, "name"=> "F-MAX",  "slug"=> "f-max"],
["parent_id"=> 94, "name"=> "Focus RS",  "slug"=> "focus-rs"],
["parent_id"=> 94, "name"=> "Focus ST",  "slug"=> "focus-st"],
["parent_id"=> 94, "name"=> "Freda",  "slug"=> "freda"],
["parent_id"=> 94, "name"=> "Freestar",  "slug"=> "freestar"],
["parent_id"=> 94, "name"=> "Freestyle",  "slug"=> "freestyle"],
["parent_id"=> 94, "name"=> "Galaxie",  "slug"=> "galaxie"],
["parent_id"=> 94, "name"=> "Galaxy",  "slug"=> "galaxy"],
["parent_id"=> 94, "name"=> "GPA",  "slug"=> "gpa"],
["parent_id"=> 94, "name"=> "Granada",  "slug"=> "granada"],
["parent_id"=> 94, "name"=> "GT",  "slug"=> "gt"],
["parent_id"=> 94, "name"=> "GT40",  "slug"=> "gt40"],
["parent_id"=> 94, "name"=> "Ikon",  "slug"=> "ikon"],
["parent_id"=> 94, "name"=> "Ixion",  "slug"=> "ixion"],
["parent_id"=> 94, "name"=> "KA",  "slug"=> "ka"],
["parent_id"=> 94, "name"=> "Laser",  "slug"=> "laser"],
["parent_id"=> 94, "name"=> "LTD Crown Victoria",  "slug"=> "ltd-crown-victoria"],
["parent_id"=> 94, "name"=> "M151",  "slug"=> "m151"],
["parent_id"=> 94, "name"=> "Mainline",  "slug"=> "mainline"],
["parent_id"=> 94, "name"=> "Maverick",  "slug"=> "maverick"],
["parent_id"=> 94, "name"=> "Model A",  "slug"=> "model-a"],
["parent_id"=> 94, "name"=> "Model T",  "slug"=> "model-t"],
["parent_id"=> 94, "name"=> "Mondeo ST",  "slug"=> "mondeo-st"],
["parent_id"=> 94, "name"=> "Mustang Mach-E",  "slug"=> "mustang-mach-e"],
["parent_id"=> 94, "name"=> "Orion",  "slug"=> "orion"],
["parent_id"=> 94, "name"=> "Probe",  "slug"=> "probe"],
["parent_id"=> 94, "name"=> "Puma",  "slug"=> "puma"],
["parent_id"=> 94, "name"=> "Ranchero",  "slug"=> "ranchero"],
["parent_id"=> 94, "name"=> "Ranger",  "slug"=> "ranger"],
["parent_id"=> 94, "name"=> "Scorpio",  "slug"=> "scorpio"],
["parent_id"=> 94, "name"=> "Sierra",  "slug"=> "sierra"],
["parent_id"=> 94, "name"=> "S-MAX",  "slug"=> "s-max"],
["parent_id"=> 94, "name"=> "Spectron",  "slug"=> "spectron"],
["parent_id"=> 94, "name"=> "Taunus",  "slug"=> "taunus"],
["parent_id"=> 94, "name"=> "Taurus",  "slug"=> "taurus"],
["parent_id"=> 94, "name"=> "Taurus X",  "slug"=> "taurus-x"],
["parent_id"=> 94, "name"=> "Telstar",  "slug"=> "telstar"],
["parent_id"=> 94, "name"=> "Tempo",  "slug"=> "tempo"],
["parent_id"=> 94, "name"=> "Territory",  "slug"=> "territory"],
["parent_id"=> 94, "name"=> "Thunderbird",  "slug"=> "thunderbird"],
["parent_id"=> 94, "name"=> "Torino",  "slug"=> "torino"],
["parent_id"=> 94, "name"=> "Tourneo Courier",  "slug"=> "tourneo-courier"],
["parent_id"=> 94, "name"=> "V8",  "slug"=> "v8"],
["parent_id"=> 94, "name"=> "Windstar",  "slug"=> "windstar"],
["parent_id"=> 94, "name"=> "Zephyr",  "slug"=> "zephyr"],
["parent_id"=> 95, "name"=> "Midi",  "slug"=> "midi"],
["parent_id"=> 95, "name"=> "Sauvana",  "slug"=> "sauvana"],
["parent_id"=> 95, "name"=> "Tunland",  "slug"=> "tunland"],
["parent_id"=> 95, "name"=> "Auman BJ10",  "slug"=> "auman-bj10"],
["parent_id"=> 95, "name"=> "Auman BJ11",  "slug"=> "auman-bj11"],
["parent_id"=> 95, "name"=> "Auman BJ32",  "slug"=> "auman-bj32"],
["parent_id"=> 95, "name"=> "Auman BJ33",  "slug"=> "auman-bj33"],
["parent_id"=> 95, "name"=> "Auman BJ425",  "slug"=> "auman-bj425"],
["parent_id"=> 95, "name"=> "Auman BJ51",  "slug"=> "auman-bj51"],
["parent_id"=> 95, "name"=> "Auman EST-A",  "slug"=> "auman-est-a"],
["parent_id"=> 95, "name"=> "Aumark BJ10",  "slug"=> "aumark-bj10"],
["parent_id"=> 95, "name"=> "Ollin BJ10",  "slug"=> "ollin-bj10"],
["parent_id"=> 96, "name"=> "125p",  "slug"=> "125p"],
["parent_id"=> 96, "name"=> "126p",  "slug"=> "126p"],
["parent_id"=> 96, "name"=> "127p",  "slug"=> "127p"],
["parent_id"=> 96, "name"=> "132p",  "slug"=> "132p"],
["parent_id"=> 96, "name"=> "Polonez",  "slug"=> "polonez"],
["parent_id"=> 97, "name"=> "6500 (Land King)",  "slug"=> "6500-land-king"],
["parent_id"=> 98, "name"=> "Gonow (Way)",  "slug"=> "gonow-way"],
["parent_id"=> 98, "name"=> "GS5",  "slug"=> "gs5"],
["parent_id"=> 98, "name"=> "GA3",  "slug"=> "ga3"],
["parent_id"=> 98, "name"=> "GA5",  "slug"=> "ga5"],
["parent_id"=> 98, "name"=> "GN8",  "slug"=> "gn8"],
["parent_id"=> 98, "name"=> "GS4",  "slug"=> "gs4"],
["parent_id"=> 98, "name"=> "GS8 Trumpchi",  "slug"=> "trumpchi-gs8"],
["parent_id"=> 99, "name"=> "CK (Otaka)",  "slug"=> "ck-otaka"],
["parent_id"=> 99, "name"=> "Emgrand EC7",  "slug"=> "emgrand-ec7"],
["parent_id"=> 99, "name"=> "MK",  "slug"=> "mk"],
["parent_id"=> 99, "name"=> "TX4",  "slug"=> "tx4"],
["parent_id"=> 99, "name"=> "Atlas Pro",  "slug"=> "atlas-pro"],
["parent_id"=> 99, "name"=> "Beauty Leopard",  "slug"=> "beauty-leopard"],
["parent_id"=> 99, "name"=> "Coolray",  "slug"=> "coolray"],
["parent_id"=> 99, "name"=> "Emgrand",  "slug"=> "emgrand"],
["parent_id"=> 99, "name"=> "Emgrand 7",  "slug"=> "emgrand-7"],
["parent_id"=> 99, "name"=> "Emgrand EC8",  "slug"=> "emgrand-ec8"],
["parent_id"=> 99, "name"=> "Emgrand GS",  "slug"=> "emgrand-gs"],
["parent_id"=> 99, "name"=> "Emgrand GT",  "slug"=> "emgrand-gt"],
["parent_id"=> 99, "name"=> "Emgrand X7",  "slug"=> "emgrand-x7"],
["parent_id"=> 99, "name"=> "FC (Vision)",  "slug"=> "fc-vision"],
["parent_id"=> 99, "name"=> "GC6",  "slug"=> "gc6"],
["parent_id"=> 99, "name"=> "GC9",  "slug"=> "gc9"],
["parent_id"=> 99, "name"=> "Haoqing",  "slug"=> "haoqing"],
["parent_id"=> 99, "name"=> "LC (Panda)",  "slug"=> "lc-panda"],
["parent_id"=> 99, "name"=> "LC (Panda) Cross",  "slug"=> "lc-panda-cross"],
["parent_id"=> 99, "name"=> "MK Cross",  "slug"=> "mk-cross"],
["parent_id"=> 99, "name"=> "Monjaro",  "slug"=> "monjaro"],
["parent_id"=> 99, "name"=> "MR",  "slug"=> "mr"],
["parent_id"=> 99, "name"=> "Okavango",  "slug"=> "okavango"],
["parent_id"=> 99, "name"=> "SC7",  "slug"=> "sc7"],
["parent_id"=> 99, "name"=> "Tugella",  "slug"=> "tugella"],
["parent_id"=> 100, "name"=> "G70",  "slug"=> "g70"],
["parent_id"=> 100, "name"=> "G80",  "slug"=> "g80"],
["parent_id"=> 100, "name"=> "G90",  "slug"=> "g90"],
["parent_id"=> 100, "name"=> "GV60",  "slug"=> "gv60"],
["parent_id"=> 100, "name"=> "GV70",  "slug"=> "gv70"],
["parent_id"=> 100, "name"=> "GV80",  "slug"=> "gv80"],
["parent_id"=> 101, "name"=> "Spectrum",  "slug"=> "spectrum"],
["parent_id"=> 101, "name"=> "Storm",  "slug"=> "storm"],
["parent_id"=> 101, "name"=> "Tracker",  "slug"=> "tracker-"],
["parent_id"=> 101, "name"=> "Metro",  "slug"=> "metro"],
["parent_id"=> 101, "name"=> "Prizm",  "slug"=> "prizm"],
["parent_id"=> 102, "name"=> "Acadia",  "slug"=> "acadia"],
["parent_id"=> 102, "name"=> "Savana",  "slug"=> "savana"],
["parent_id"=> 102, "name"=> "Terrain",  "slug"=> "terrain"],
["parent_id"=> 102, "name"=> "Yukon",  "slug"=> "yukon"],
["parent_id"=> 102, "name"=> "100",  "slug"=> "100"],
["parent_id"=> 102, "name"=> "Canyon",  "slug"=> "canyon"],
["parent_id"=> 102, "name"=> "Envoy",  "slug"=> "envoy"],
["parent_id"=> 102, "name"=> "Jimmy",  "slug"=> "jimmy"],
["parent_id"=> 102, "name"=> "Safari",  "slug"=> "safari"],
["parent_id"=> 102, "name"=> "Sierra",  "slug"=> "sierra"],
["parent_id"=> 102, "name"=> "Sonoma",  "slug"=> "sonoma"],
["parent_id"=> 102, "name"=> "Suburban",  "slug"=> "suburban"],
["parent_id"=> 102, "name"=> "Syclone",  "slug"=> "syclone"],
["parent_id"=> 102, "name"=> "Typhoon",  "slug"=> "typhoon"],
["parent_id"=> 102, "name"=> "Vandura",  "slug"=> "vandura"],
["parent_id"=> 103, "name"=> "Troy",  "slug"=> "troy"], 
["parent_id"=> 103, "name"=> "Victor",  "slug"=> "victor"],
["parent_id"=> 104, "name"=> "Roadster",  "slug"=> "roadster"],
["parent_id"=> 105, "name"=> "Madison",  "slug"=> "madison"],
["parent_id"=> 106, "name"=> "Hover H3",  "slug"=> "hover-h3"],
["parent_id"=> 106, "name"=> "Hover H5",  "slug"=> "hover-h5"],
["parent_id"=> 106, "name"=> "Hover H6",  "slug"=> "hover-h6"],
["parent_id"=> 106, "name"=> "Hover M2",  "slug"=> "hover-m2"],
["parent_id"=> 106, "name"=> "Hover M4",  "slug"=> "hover-m4"],
["parent_id"=> 106, "name"=> "Pegasus",  "slug"=> "pegasus"],
["parent_id"=> 106, "name"=> "Sailor",  "slug"=> "sailor"],
["parent_id"=> 106, "name"=> "Voleex C30",  "slug"=> "voleex-c30"],
["parent_id"=> 106, "name"=> "Voleex C50",  "slug"=> "voleex-c50"],
["parent_id"=> 106, "name"=> "Wingle",  "slug"=> "wingle"],
["parent_id"=> 106, "name"=> "Coolbear",  "slug"=> "coolbear"],
["parent_id"=> 106, "name"=> "Cowry (V80)",  "slug"=> "cowry-v80"],
["parent_id"=> 106, "name"=> "Deer",  "slug"=> "deer"],
["parent_id"=> 106, "name"=> "Florid",  "slug"=> "florid"],
["parent_id"=> 106, "name"=> "Hover",  "slug"=> "hover"],
["parent_id"=> 106, "name"=> "Hover M1 (Peri 4x4)",  "slug"=> "hover-m1-peri-4x4"],
["parent_id"=> 106, "name"=> "Hover Pi",  "slug"=> "hover-pi"],
["parent_id"=> 106, "name"=> "Pao",  "slug"=> "pao"],
["parent_id"=> 106, "name"=> "Peri",  "slug"=> "peri"],
["parent_id"=> 106, "name"=> "Poer",  "slug"=> "poer"],
["parent_id"=> 106, "name"=> "Safe",  "slug"=> "safe"],
["parent_id"=> 106, "name"=> "Sing RUV",  "slug"=> "sing-ruv"],
["parent_id"=> 106, "name"=> "Socool",  "slug"=> "socool"],
["parent_id"=> 106, "name"=> "Tank 600",  "slug"=> "tank-600"],
["parent_id"=> 106, "name"=> "Voleex C10 (Phenom)",  "slug"=> "voleex-c10-phenom"],
["parent_id"=> 106, "name"=> "Voleex C20R",  "slug"=> "voleex-c20r"],
["parent_id"=> 107, "name"=> "Brio",  "slug"=> "brio"],
["parent_id"=> 107, "name"=> "Princip",  "slug"=> "princip"],
["parent_id"=> 107, "name"=> "Saibao",  "slug"=> "saibao"],
["parent_id"=> 107, "name"=> "Sigma",  "slug"=> "sigma"],
["parent_id"=> 107, "name"=> "Simbo",  "slug"=> "simbo"],
["parent_id"=> 108, "name"=> "2",  "slug"=> "2"],
["parent_id"=> 108, "name"=> "3",  "slug"=> "3"],
["parent_id"=> 108, "name"=> "7",  "slug"=> "7"],
["parent_id"=> 108, "name"=> "M3",  "slug"=> "m3"],
["parent_id"=> 108, "name"=> "8S",  "slug"=> "8s"],
["parent_id"=> 108, "name"=> "Family",  "slug"=> "family"],
["parent_id"=> 108, "name"=> "Family F7",  "slug"=> "family-f7"],
["parent_id"=> 108, "name"=> "Freema",  "slug"=> "freema"],
["parent_id"=> 108, "name"=> "S5",  "slug"=> "s5"],
["parent_id"=> 109, "name"=> "Rekord",  "slug"=> "rekord"],
["parent_id"=> 109, "name"=> "Typ 13",  "slug"=> "typ-13"],
["parent_id"=> 110, "name"=> "H2",  "slug"=> "h2"],
["parent_id"=> 110, "name"=> "H6",  "slug"=> "h6"],
["parent_id"=> 110, "name"=> "H8",  "slug"=> "h8"],
["parent_id"=> 110, "name"=> "H9",  "slug"=> "h9"],
["parent_id"=> 110, "name"=> "Dargo",  "slug"=> "dargo"],
["parent_id"=> 110, "name"=> "F7",  "slug"=> "f7"],
["parent_id"=> 110, "name"=> "F7x",  "slug"=> "f7x"],
["parent_id"=> 110, "name"=> "H5",  "slug"=> "h5"],
["parent_id"=> 110, "name"=> "H6S (Coupe)",  "slug"=> "h6s-coupe"],
["parent_id"=> 110, "name"=> "Jolion",  "slug"=> "jolion"],
["parent_id"=> 111, "name"=> "B21",  "slug"=> "b21"],
["parent_id"=> 111, "name"=> "Boliger",  "slug"=> "boliger"],
["parent_id"=> 111, "name"=> "Laville",  "slug"=> "laville"],
["parent_id"=> 112, "name"=> "Typ 154",  "slug"=> "typ-154"],
["parent_id"=> 113, "name"=> "Ambassador",  "slug"=> "ambassador"],
["parent_id"=> 113, "name"=> "Contessa",  "slug"=> "contessa"],
["parent_id"=> 114, "name"=> "K6",  "slug"=> "k6"],
["parent_id"=> 115, "name"=> "Caprice",  "slug"=> "caprice"],
["parent_id"=> 115, "name"=> "Cruze",  "slug"=> "cruze"],
["parent_id"=> 115, "name"=> "Frontera",  "slug"=> "frontera"],
["parent_id"=> 115, "name"=> "Jackaroo",  "slug"=> "jackaroo"],
["parent_id"=> 115, "name"=> "Monaro",  "slug"=> "monaro"],
["parent_id"=> 115, "name"=> "Apollo",  "slug"=> "apollo"],
["parent_id"=> 115, "name"=> "Astra",  "slug"=> "astra"],
["parent_id"=> 115, "name"=> "Barina",  "slug"=> "barina"],
["parent_id"=> 115, "name"=> "Calais",  "slug"=> "calais"],
["parent_id"=> 115, "name"=> "Commodore",  "slug"=> "commodore"],
["parent_id"=> 115, "name"=> "Rodeo",  "slug"=> "rodeo"],
["parent_id"=> 115, "name"=> "Statesman",  "slug"=> "statesman"],
["parent_id"=> 115, "name"=> "UTE",  "slug"=> "ute"],
["parent_id"=> 115, "name"=> "Vectra",  "slug"=> "vectra"],
["parent_id"=> 115, "name"=> "Zafira",  "slug"=> "zafira"],
["parent_id"=> 116, "name"=> "Accord",  "slug"=> "accord"],
["parent_id"=> 116, "name"=> "Civic",  "slug"=> "civic"],
["parent_id"=> 116, "name"=> "CR-V",  "slug"=> "cr-v"],
["parent_id"=> 116, "name"=> "Insight",  "slug"=> "insight"],
["parent_id"=> 116, "name"=> "Pilot",  "slug"=> "pilot"],
["parent_id"=> 116, "name"=> "145",  "slug"=> "145"],
["parent_id"=> 116, "name"=> "Acty",  "slug"=> "acty"],
["parent_id"=> 116, "name"=> "Airwave",  "slug"=> "airwave"],
["parent_id"=> 116, "name"=> "Ascot",  "slug"=> "ascot"],
["parent_id"=> 116, "name"=> "Ascot Innova",  "slug"=> "ascot-innova"],
["parent_id"=> 116, "name"=> "Avancier",  "slug"=> "avancier"],
["parent_id"=> 116, "name"=> "Ballade",  "slug"=> "ballade"],
["parent_id"=> 116, "name"=> "Beat",  "slug"=> "beat"],
["parent_id"=> 116, "name"=> "Brio",  "slug"=> "brio"],
["parent_id"=> 116, "name"=> "Capa",  "slug"=> "capa"],
["parent_id"=> 116, "name"=> "City",  "slug"=> "city"],
["parent_id"=> 116, "name"=> "Civic Ferio",  "slug"=> "civic-ferio"],
["parent_id"=> 116, "name"=> "Civic Type R",  "slug"=> "civic-type-r"],
["parent_id"=> 116, "name"=> "Concerto",  "slug"=> "concerto"],
["parent_id"=> 116, "name"=> "Crossroad",  "slug"=> "crossroad"],
["parent_id"=> 116, "name"=> "Crosstour",  "slug"=> "crosstour"],
["parent_id"=> 116, "name"=> "CR-X",  "slug"=> "cr-x"],
["parent_id"=> 116, "name"=> "CR-Z",  "slug"=> "cr-z"],
["parent_id"=> 116, "name"=> "Domani",  "slug"=> "domani"],
["parent_id"=> 116, "name"=> "e",  "slug"=> "e"],
["parent_id"=> 116, "name"=> "Edix",  "slug"=> "edix"],
["parent_id"=> 116, "name"=> "Element",  "slug"=> "element"],
["parent_id"=> 116, "name"=> "Elysion",  "slug"=> "elysion"],
["parent_id"=> 116, "name"=> "e=>NS1",  "slug"=> "ens1"],
["parent_id"=> 116, "name"=> "FCX Clarity",  "slug"=> "fcx-clarity"],
["parent_id"=> 116, "name"=> "Fit",  "slug"=> "fit"],
["parent_id"=> 116, "name"=> "Fit Aria",  "slug"=> "fit-aria"],
["parent_id"=> 116, "name"=> "Fit Shuttle",  "slug"=> "fit-shuttle"],
["parent_id"=> 116, "name"=> "Freed",  "slug"=> "freed"],
["parent_id"=> 116, "name"=> "FR-V",  "slug"=> "fr-v"],
["parent_id"=> 116, "name"=> "Grace",  "slug"=> "grace"],
["parent_id"=> 116, "name"=> "Horizon",  "slug"=> "horizon"],
["parent_id"=> 116, "name"=> "HR-V",  "slug"=> "hr-v"],
["parent_id"=> 116, "name"=> "Inspire",  "slug"=> "inspire"],
["parent_id"=> 116, "name"=> "Integra",  "slug"=> "integra"],
["parent_id"=> 116, "name"=> "Integra SJ",  "slug"=> "integra-sj"],
["parent_id"=> 116, "name"=> "Jade",  "slug"=> "jade"],
["parent_id"=> 116, "name"=> "Jazz",  "slug"=> "jazz"],
["parent_id"=> 116, "name"=> "Lagreat",  "slug"=> "lagreat"],
["parent_id"=> 116, "name"=> "Legend",  "slug"=> "legend"],
["parent_id"=> 116, "name"=> "Life",  "slug"=> "life"],
["parent_id"=> 116, "name"=> "Logo",  "slug"=> "logo"],
["parent_id"=> 116, "name"=> "MDX",  "slug"=> "mdx"],
["parent_id"=> 116, "name"=> "M-NV",  "slug"=> "m-nv--"],
["parent_id"=> 116, "name"=> "Mobilio",  "slug"=> "mobilio"],
["parent_id"=> 116, "name"=> "Mobilio Spike",  "slug"=> "mobilio-spike"],
["parent_id"=> 116, "name"=> "N360",  "slug"=> "n360"],
["parent_id"=> 116, "name"=> "N-BOX",  "slug"=> "n-box"],
["parent_id"=> 116, "name"=> "N-BOX Slash",  "slug"=> "n-box-slash"],
["parent_id"=> 116, "name"=> "N-One",  "slug"=> "n-one"],
["parent_id"=> 116, "name"=> "NSX",  "slug"=> "nsx"],
["parent_id"=> 116, "name"=> "N-WGN",  "slug"=> "n-wgn"],
["parent_id"=> 116, "name"=> "Odyssey",  "slug"=> "odyssey"],
["parent_id"=> 116, "name"=> "Odyssey (North America)",  "slug"=> "odyssey-north-america"],
["parent_id"=> 116, "name"=> "Orthia",  "slug"=> "orthia"],
["parent_id"=> 116, "name"=> "Partner",  "slug"=> "partner"],
["parent_id"=> 116, "name"=> "Passport",  "slug"=> "passport"],
["parent_id"=> 116, "name"=> "Prelude",  "slug"=> "prelude"],
["parent_id"=> 116, "name"=> "Quint",  "slug"=> "quint"],
["parent_id"=> 116, "name"=> "Rafaga",  "slug"=> "rafaga"],
["parent_id"=> 116, "name"=> "Ridgeline",  "slug"=> "ridgeline"],
["parent_id"=> 116, "name"=> "S2000",  "slug"=> "s2000"],
["parent_id"=> 116, "name"=> "S500",  "slug"=> "s500"],
["parent_id"=> 116, "name"=> "S600",  "slug"=> "s600"],
["parent_id"=> 116, "name"=> "S660",  "slug"=> "s660"],
["parent_id"=> 116, "name"=> "Saber",  "slug"=> "saber"],
["parent_id"=> 116, "name"=> "Shuttle",  "slug"=> "shuttle"],
["parent_id"=> 116, "name"=> "S-MX",  "slug"=> "s-mx"],
["parent_id"=> 116, "name"=> "Stepwgn",  "slug"=> "stepwgn"],
["parent_id"=> 116, "name"=> "Stream",  "slug"=> "stream"],
["parent_id"=> 116, "name"=> "Street",  "slug"=> "street"],
["parent_id"=> 116, "name"=> "That'S",  "slug"=> "thats"],
["parent_id"=> 116, "name"=> "Today",  "slug"=> "today"],
["parent_id"=> 116, "name"=> "Torneo",  "slug"=> "torneo"],
["parent_id"=> 116, "name"=> "Vamos",  "slug"=> "vamos"],
["parent_id"=> 116, "name"=> "Vezel",  "slug"=> "vezel"],
["parent_id"=> 116, "name"=> "Vigor",  "slug"=> "vigor"],
["parent_id"=> 116, "name"=> "Z",  "slug"=> "z"],
["parent_id"=> 116, "name"=> "Zest",  "slug"=> "zest"],
["parent_id"=> 117, "name"=> "HS5",  "slug"=> "hs5"],
["parent_id"=> 117, "name"=> "E-HS9",  "slug"=> "e-hs9"],
["parent_id"=> 117, "name"=> "E-QM5",  "slug"=> "e-qm5"],
["parent_id"=> 117, "name"=> "H7",  "slug"=> "h7"],
["parent_id"=> 117, "name"=> "H9",  "slug"=> "h9"],
["parent_id"=> 117, "name"=> "HS7",  "slug"=> "hs7"],
];